// AILVIE 13-language string layer.
// Core UI is already fully localized via the T dictionary. This layer localizes the many
// inline `lang==="tr"?TR:EN` strings for the other 11 languages. TL(en, lang) returns the
// translation for the current language, or the English source as a safe fallback.
// The dictionary grows in batches; medical/safety-critical strings are reviewed with extra care.
// Languages: de ru zh hi nl es ar fr pt id bn  (tr comes from the ternary; en is the source/fallback)

export const TLD = {
  // ---- Batch 1: high-frequency, context-safe UI words ----
  "Add": {de:"Hinzufügen",ru:"Добавить",zh:"添加",hi:"जोड़ें",nl:"Toevoegen",es:"Añadir",ar:"إضافة",fr:"Ajouter",pt:"Adicionar",id:"Tambah",bn:"যোগ করুন"},
  "Edit": {de:"Bearbeiten",ru:"Изменить",zh:"编辑",hi:"संपादित करें",nl:"Bewerken",es:"Editar",ar:"تعديل",fr:"Modifier",pt:"Editar",id:"Ubah",bn:"সম্পাদনা"},
  "Done": {de:"Fertig",ru:"Готово",zh:"完成",hi:"हो गया",nl:"Klaar",es:"Hecho",ar:"تم",fr:"Terminé",pt:"Concluído",id:"Selesai",bn:"সম্পন্ন"},
  "Copy": {de:"Kopieren",ru:"Копировать",zh:"复制",hi:"कॉपी",nl:"Kopiëren",es:"Copiar",ar:"نسخ",fr:"Copier",pt:"Copiar",id:"Salin",bn:"কপি"},
  "Name": {de:"Name",ru:"Имя",zh:"名称",hi:"नाम",nl:"Naam",es:"Nombre",ar:"الاسم",fr:"Nom",pt:"Nome",id:"Nama",bn:"নাম"},
  "Date": {de:"Datum",ru:"Дата",zh:"日期",hi:"तारीख",nl:"Datum",es:"Fecha",ar:"التاريخ",fr:"Date",pt:"Data",id:"Tanggal",bn:"তারিখ"},
  "Time": {de:"Zeit",ru:"Время",zh:"时间",hi:"समय",nl:"Tijd",es:"Hora",ar:"الوقت",fr:"Heure",pt:"Hora",id:"Waktu",bn:"সময়"},
  "Now": {de:"Jetzt",ru:"Сейчас",zh:"现在",hi:"अभी",nl:"Nu",es:"Ahora",ar:"الآن",fr:"Maintenant",pt:"Agora",id:"Sekarang",bn:"এখন"},
  "On": {de:"An",ru:"Вкл",zh:"开",hi:"चालू",nl:"Aan",es:"Activado",ar:"تشغيل",fr:"Activé",pt:"Ligado",id:"Aktif",bn:"চালু"},
  "Off": {de:"Aus",ru:"Выкл",zh:"关",hi:"बंद",nl:"Uit",es:"Desactivado",ar:"إيقاف",fr:"Désactivé",pt:"Desligado",id:"Nonaktif",bn:"বন্ধ"},
  "All": {de:"Alle",ru:"Все",zh:"全部",hi:"सभी",nl:"Alle",es:"Todos",ar:"الكل",fr:"Tout",pt:"Todos",id:"Semua",bn:"সব"},
  "Soon": {de:"Bald",ru:"Скоро",zh:"即将",hi:"जल्द",nl:"Binnenkort",es:"Pronto",ar:"قريبًا",fr:"Bientôt",pt:"Em breve",id:"Segera",bn:"শীঘ্রই"},
  "Good": {de:"Gut",ru:"Хорошо",zh:"良好",hi:"अच्छा",nl:"Goed",es:"Bien",ar:"جيد",fr:"Bon",pt:"Bom",id:"Baik",bn:"ভালো"},
  "Male": {de:"Männlich",ru:"Мужской",zh:"男",hi:"पुरुष",nl:"Man",es:"Hombre",ar:"ذكر",fr:"Homme",pt:"Masculino",id:"Pria",bn:"পুরুষ"},
  "Call": {de:"Anrufen",ru:"Позвонить",zh:"呼叫",hi:"कॉल",nl:"Bellen",es:"Llamar",ar:"اتصال",fr:"Appeler",pt:"Ligar",id:"Panggil",bn:"কল"},
  "Left": {de:"Übrig",ru:"Осталось",zh:"剩余",hi:"बाकी",nl:"Over",es:"Restante",ar:"متبقٍ",fr:"Restant",pt:"Restante",id:"Sisa",bn:"বাকি"},
  "Mood": {de:"Stimmung",ru:"Настроение",zh:"心情",hi:"मूड",nl:"Stemming",es:"Ánimo",ar:"المزاج",fr:"Humeur",pt:"Humor",id:"Suasana hati",bn:"মেজাজ"},
  "Live": {de:"Live",ru:"Онлайн",zh:"实时",hi:"लाइव",nl:"Live",es:"En vivo",ar:"مباشر",fr:"En direct",pt:"Ao vivo",id:"Langsung",bn:"লাইভ"},
  "Fast": {de:"Schnell",ru:"Быстро",zh:"快",hi:"तेज़",nl:"Snel",es:"Rápido",ar:"سريع",fr:"Rapide",pt:"Rápido",id:"Cepat",bn:"দ্রুত"},
  "Slow": {de:"Langsam",ru:"Медленно",zh:"慢",hi:"धीमा",nl:"Langzaam",es:"Lento",ar:"بطيء",fr:"Lent",pt:"Lento",id:"Lambat",bn:"ধীর"},
  "Wake": {de:"Aufwachen",ru:"Подъём",zh:"起床",hi:"जागना",nl:"Wakker",es:"Despertar",ar:"الاستيقاظ",fr:"Réveil",pt:"Acordar",id:"Bangun",bn:"জাগরণ"},
  "Taxi": {de:"Taxi",ru:"Такси",zh:"出租车",hi:"टैक्सी",nl:"Taxi",es:"Taxi",ar:"سيارة أجرة",fr:"Taxi",pt:"Táxi",id:"Taksi",bn:"ট্যাক্সি"},

  // ---- Batch 2: common readable UI phrases ----
  "Signed out": {de:"Abgemeldet",ru:"Выход выполнен",zh:"已退出",hi:"साइन आउट",nl:"Afgemeld",es:"Sesión cerrada",ar:"تم تسجيل الخروج",fr:"Déconnecté",pt:"Sessão encerrada",id:"Keluar",bn:"সাইন আউট"},
  "Signed in": {de:"Angemeldet",ru:"Вход выполнен",zh:"已登录",hi:"साइन इन",nl:"Aangemeld",es:"Sesión iniciada",ar:"تم تسجيل الدخول",fr:"Connecté",pt:"Sessão iniciada",id:"Masuk",bn:"সাইন ইন"},
  "Enter data": {de:"Daten eingeben",ru:"Ввести данные",zh:"输入数据",hi:"डेटा दर्ज करें",nl:"Gegevens invoeren",es:"Ingresar datos",ar:"إدخال البيانات",fr:"Saisir des données",pt:"Inserir dados",id:"Masukkan data",bn:"তথ্য দিন"},
  "Taken Meds": {de:"Eingenommene Medikamente",ru:"Принятые лекарства",zh:"已服药物",hi:"ली गई दवाएं",nl:"Ingenomen medicijnen",es:"Medicamentos tomados",ar:"الأدوية المتناولة",fr:"Médicaments pris",pt:"Medicamentos tomados",id:"Obat yang diminum",bn:"নেওয়া ওষুধ"},
  "How to use": {de:"Anleitung",ru:"Как пользоваться",zh:"使用方法",hi:"उपयोग कैसे करें",nl:"Hoe te gebruiken",es:"Cómo usar",ar:"كيفية الاستخدام",fr:"Comment utiliser",pt:"Como usar",id:"Cara pakai",bn:"যেভাবে ব্যবহার করবেন"},
  "Identifier": {de:"Kennung",ru:"Идентификатор",zh:"标识符",hi:"पहचानकर्ता",nl:"Identificatie",es:"Identificador",ar:"المعرّف",fr:"Identifiant",pt:"Identificador",id:"Pengenal",bn:"শনাক্তকারী"},
  "Biometrics": {de:"Biometrie",ru:"Биометрия",zh:"生物识别",hi:"बायोमेट्रिक्स",nl:"Biometrie",es:"Biometría",ar:"القياسات الحيوية",fr:"Biométrie",pt:"Biometria",id:"Biometrik",bn:"বায়োমেট্রিক্স"},
  "Contact Us": {de:"Kontakt",ru:"Связаться с нами",zh:"联系我们",hi:"संपर्क करें",nl:"Contact",es:"Contáctanos",ar:"اتصل بنا",fr:"Nous contacter",pt:"Fale conosco",id:"Hubungi kami",bn:"যোগাযোগ করুন"},
  "Empty note": {de:"Leere Notiz",ru:"Пустая заметка",zh:"空笔记",hi:"खाली नोट",nl:"Lege notitie",es:"Nota vacía",ar:"ملاحظة فارغة",fr:"Note vide",pt:"Nota vazia",id:"Catatan kosong",bn:"খালি নোট"},
  "Overweight": {de:"Übergewicht",ru:"Избыточный вес",zh:"超重",hi:"अधिक वजन",nl:"Overgewicht",es:"Sobrepeso",ar:"زيادة الوزن",fr:"Surpoids",pt:"Sobrepeso",id:"Kelebihan berat badan",bn:"অতিরিক্ত ওজন"},
  "Connection": {de:"Verbindung",ru:"Подключение",zh:"连接",hi:"कनेक्शन",nl:"Verbinding",es:"Conexión",ar:"الاتصال",fr:"Connexion",pt:"Conexão",id:"Koneksi",bn:"সংযোগ"},
  "Take photo": {de:"Foto aufnehmen",ru:"Сделать фото",zh:"拍照",hi:"फोटो लें",nl:"Foto maken",es:"Tomar foto",ar:"التقاط صورة",fr:"Prendre une photo",pt:"Tirar foto",id:"Ambil foto",bn:"ছবি তুলুন"},
  "Disconnect": {de:"Trennen",ru:"Отключить",zh:"断开",hi:"डिस्कनेक्ट",nl:"Verbreken",es:"Desconectar",ar:"قطع الاتصال",fr:"Déconnecter",pt:"Desconectar",id:"Putuskan",bn:"বিচ্ছিন্ন করুন"},
  "Test again": {de:"Erneut testen",ru:"Повторить тест",zh:"重新测试",hi:"फिर से जांचें",nl:"Opnieuw testen",es:"Probar de nuevo",ar:"إعادة الاختبار",fr:"Retester",pt:"Testar novamente",id:"Uji lagi",bn:"আবার পরীক্ষা করুন"},
  "New Record": {de:"Neuer Eintrag",ru:"Новая запись",zh:"新记录",hi:"नया रिकॉर्ड",nl:"Nieuw record",es:"Nuevo registro",ar:"سجل جديد",fr:"Nouvel enregistrement",pt:"Novo registro",id:"Catatan baru",bn:"নতুন রেকর্ড"},
  "Voice call": {de:"Sprachanruf",ru:"Голосовой вызов",zh:"语音通话",hi:"वॉइस कॉल",nl:"Spraakoproep",es:"Llamada de voz",ar:"مكالمة صوتية",fr:"Appel vocal",pt:"Chamada de voz",id:"Panggilan suara",bn:"ভয়েস কল"},
  "Video call": {de:"Videoanruf",ru:"Видеозвонок",zh:"视频通话",hi:"वीडियो कॉल",nl:"Videogesprek",es:"Videollamada",ar:"مكالمة فيديو",fr:"Appel vidéo",pt:"Videochamada",id:"Panggilan video",bn:"ভিডিও কল"},
  "Conference": {de:"Konferenz",ru:"Конференция",zh:"会议",hi:"कॉन्फ्रेंस",nl:"Vergadering",es:"Conferencia",ar:"مؤتمر",fr:"Conférence",pt:"Conferência",id:"Konferensi",bn:"কনফারেন্স"},
  "Group name": {de:"Gruppenname",ru:"Название группы",zh:"群组名称",hi:"समूह का नाम",nl:"Groepsnaam",es:"Nombre del grupo",ar:"اسم المجموعة",fr:"Nom du groupe",pt:"Nome do grupo",id:"Nama grup",bn:"গ্রুপের নাম"},
  "Navigation": {de:"Navigation",ru:"Навигация",zh:"导航",hi:"नेविगेशन",nl:"Navigatie",es:"Navegación",ar:"الملاحة",fr:"Navigation",pt:"Navegação",id:"Navigasi",bn:"নেভিগেশন"},
  "Background": {de:"Hintergrund",ru:"Фон",zh:"背景",hi:"पृष्ठभूमि",nl:"Achtergrond",es:"Fondo",ar:"الخلفية",fr:"Arrière-plan",pt:"Fundo",id:"Latar belakang",bn:"পটভূমি"},
  "Formatting": {de:"Formatierung",ru:"Форматирование",zh:"格式",hi:"फ़ॉर्मेटिंग",nl:"Opmaak",es:"Formato",ar:"التنسيق",fr:"Mise en forme",pt:"Formatação",id:"Pemformatan",bn:"ফরম্যাটিং"},
  "Reset zoom": {de:"Zoom zurücksetzen",ru:"Сбросить масштаб",zh:"重置缩放",hi:"ज़ूम रीसेट करें",nl:"Zoom resetten",es:"Restablecer zoom",ar:"إعادة ضبط التكبير",fr:"Réinitialiser le zoom",pt:"Redefinir zoom",id:"Atur ulang zoom",bn:"জুম রিসেট"},
  "My account": {de:"Mein Konto",ru:"Мой аккаунт",zh:"我的账户",hi:"मेरा खाता",nl:"Mijn account",es:"Mi cuenta",ar:"حسابي",fr:"Mon compte",pt:"Minha conta",id:"Akun saya",bn:"আমার অ্যাকাউন্ট"},
  "Live Health": {de:"Live-Gesundheit",ru:"Здоровье в реальном времени",zh:"实时健康",hi:"लाइव हेल्थ",nl:"Live gezondheid",es:"Salud en vivo",ar:"الصحة المباشرة",fr:"Santé en direct",pt:"Saúde ao vivo",id:"Kesehatan langsung",bn:"লাইভ স্বাস্থ্য"},
  "Unlock sync": {de:"Sync entsperren",ru:"Разблокировать синхронизацию",zh:"解锁同步",hi:"सिंक अनलॉक करें",nl:"Sync ontgrendelen",es:"Desbloquear sincronización",ar:"فتح المزامنة",fr:"Déverrouiller la sync",pt:"Desbloquear sincronização",id:"Buka kunci sinkronisasi",bn:"সিঙ্ক আনলক"},
  "Remove lock": {de:"Sperre entfernen",ru:"Убрать блокировку",zh:"移除锁定",hi:"लॉक हटाएं",nl:"Vergrendeling verwijderen",es:"Quitar bloqueo",ar:"إزالة القفل",fr:"Supprimer le verrou",pt:"Remover bloqueio",id:"Hapus kunci",bn:"লক সরান"},
  "Active Plan": {de:"Aktiver Plan",ru:"Активный план",zh:"当前套餐",hi:"सक्रिय योजना",nl:"Actief abonnement",es:"Plan activo",ar:"الخطة النشطة",fr:"Forfait actif",pt:"Plano ativo",id:"Paket aktif",bn:"সক্রিয় প্ল্যান"},
  "Data Backup": {de:"Datensicherung",ru:"Резервная копия",zh:"数据备份",hi:"डेटा बैकअप",nl:"Gegevensback-up",es:"Copia de seguridad",ar:"نسخ البيانات احتياطيًا",fr:"Sauvegarde des données",pt:"Backup de dados",id:"Cadangan data",bn:"ডেটা ব্যাকআপ"},
  "Select meal": {de:"Mahlzeit wählen",ru:"Выбрать приём пищи",zh:"选择餐次",hi:"भोजन चुनें",nl:"Maaltijd kiezen",es:"Seleccionar comida",ar:"اختر الوجبة",fr:"Choisir un repas",pt:"Selecionar refeição",id:"Pilih makanan",bn:"খাবার নির্বাচন করুন"},
  "Add Reading": {de:"Messwert hinzufügen",ru:"Добавить измерение",zh:"添加读数",hi:"रीडिंग जोड़ें",nl:"Meting toevoegen",es:"Añadir medición",ar:"إضافة قراءة",fr:"Ajouter une mesure",pt:"Adicionar leitura",id:"Tambah pengukuran",bn:"রিডিং যোগ করুন"},
  "Goal weight": {de:"Zielgewicht",ru:"Целевой вес",zh:"目标体重",hi:"लक्ष्य वजन",nl:"Streefgewicht",es:"Peso objetivo",ar:"الوزن المستهدف",fr:"Poids cible",pt:"Peso alvo",id:"Berat target",bn:"লক্ষ্য ওজন"},
  "Vital Signs": {de:"Vitalzeichen",ru:"Показатели жизнедеятельности",zh:"生命体征",hi:"महत्वपूर्ण संकेत",nl:"Vitale functies",es:"Signos vitales",ar:"العلامات الحيوية",fr:"Signes vitaux",pt:"Sinais vitais",id:"Tanda vital",bn:"শারীরিক লক্ষণ"},
  "Vital signs": {de:"Vitalzeichen",ru:"Показатели жизнедеятельности",zh:"生命体征",hi:"महत्वपूर्ण संकेत",nl:"Vitale functies",es:"Signos vitales",ar:"العلامات الحيوية",fr:"Signes vitaux",pt:"Sinais vitais",id:"Tanda vital",bn:"শারীরিক লক্ষণ"},
  "Last 7 days": {de:"Letzte 7 Tage",ru:"Последние 7 дней",zh:"最近7天",hi:"पिछले 7 दिन",nl:"Laatste 7 dagen",es:"Últimos 7 días",ar:"آخر 7 أيام",fr:"7 derniers jours",pt:"Últimos 7 dias",id:"7 hari terakhir",bn:"গত ৭ দিন"},
  "New group": {de:"Neue Gruppe",ru:"Новая группа",zh:"新群组",hi:"नया समूह",nl:"Nieuwe groep",es:"Nuevo grupo",ar:"مجموعة جديدة",fr:"Nouveau groupe",pt:"Novo grupo",id:"Grup baru",bn:"নতুন গ্রুপ"},
  "Underweight": {de:"Untergewicht",ru:"Недостаточный вес",zh:"体重过轻",hi:"कम वजन",nl:"Ondergewicht",es:"Bajo peso",ar:"نقص الوزن",fr:"Insuffisance pondérale",pt:"Abaixo do peso",id:"Berat badan kurang",bn:"কম ওজন"},
  "Add photo": {de:"Foto hinzufügen",ru:"Добавить фото",zh:"添加照片",hi:"फोटो जोड़ें",nl:"Foto toevoegen",es:"Añadir foto",ar:"إضافة صورة",fr:"Ajouter une photo",pt:"Adicionar foto",id:"Tambah foto",bn:"ছবি যোগ করুন"},
  "Try again": {de:"Erneut versuchen",ru:"Повторить",zh:"重试",hi:"पुनः प्रयास करें",nl:"Opnieuw proberen",es:"Reintentar",ar:"حاول مرة أخرى",fr:"Réessayer",pt:"Tentar novamente",id:"Coba lagi",bn:"আবার চেষ্টা করুন"},
  "Delete all": {de:"Alle löschen",ru:"Удалить все",zh:"全部删除",hi:"सभी हटाएं",nl:"Alles verwijderen",es:"Eliminar todo",ar:"حذف الكل",fr:"Tout supprimer",pt:"Excluir tudo",id:"Hapus semua",bn:"সব মুছুন"},

  // ---- Batch 3: dialogs, actions, health labels ----
  "Coming soon": {de:"Bald verfügbar",ru:"Скоро",zh:"即将推出",hi:"जल्द आ रहा है",nl:"Binnenkort",es:"Próximamente",ar:"قريبًا",fr:"Bientôt disponible",pt:"Em breve",id:"Segera hadir",bn:"শীঘ্রই আসছে"},
  "No compass": {de:"Kein Kompass",ru:"Нет компаса",zh:"无指南针",hi:"कोई कम्पास नहीं",nl:"Geen kompas",es:"Sin brújula",ar:"لا توجد بوصلة",fr:"Pas de boussole",pt:"Sem bússola",id:"Tidak ada kompas",bn:"কম্পাস নেই"},
  "Enterprise": {de:"Unternehmen",ru:"Корпоративный",zh:"企业版",hi:"एंटरप्राइज़",nl:"Zakelijk",es:"Empresas",ar:"للمؤسسات",fr:"Entreprise",pt:"Corporativo",id:"Perusahaan",bn:"এন্টারপ্রাইজ"},
  "Checkboxes": {de:"Kontrollkästchen",ru:"Флажки",zh:"复选框",hi:"चेकबॉक्स",nl:"Selectievakjes",es:"Casillas",ar:"مربعات الاختيار",fr:"Cases à cocher",pt:"Caixas de seleção",id:"Kotak centang",bn:"চেকবক্স"},
  "Lower bound": {de:"Untergrenze",ru:"Нижняя граница",zh:"下限",hi:"निचली सीमा",nl:"Ondergrens",es:"Límite inferior",ar:"الحد الأدنى",fr:"Limite inférieure",pt:"Limite inferior",id:"Batas bawah",bn:"নিম্নসীমা"},
  "Upper bound": {de:"Obergrenze",ru:"Верхняя граница",zh:"上限",hi:"ऊपरी सीमा",nl:"Bovengrens",es:"Límite superior",ar:"الحد الأقصى",fr:"Limite supérieure",pt:"Limite superior",id:"Batas atas",bn:"ঊর্ধ্বসীমা"},
  "Select unit": {de:"Einheit wählen",ru:"Выбрать единицу",zh:"选择单位",hi:"इकाई चुनें",nl:"Eenheid kiezen",es:"Seleccionar unidad",ar:"اختر الوحدة",fr:"Choisir l'unité",pt:"Selecionar unidade",id:"Pilih satuan",bn:"একক নির্বাচন"},
  "Edit Record": {de:"Eintrag bearbeiten",ru:"Изменить запись",zh:"编辑记录",hi:"रिकॉर्ड संपादित करें",nl:"Record bewerken",es:"Editar registro",ar:"تعديل السجل",fr:"Modifier l'enregistrement",pt:"Editar registro",id:"Ubah catatan",bn:"রেকর্ড সম্পাদনা"},
  "New Contact": {de:"Neuer Kontakt",ru:"Новый контакт",zh:"新联系人",hi:"नया संपर्क",nl:"Nieuw contact",es:"Nuevo contacto",ar:"جهة اتصال جديدة",fr:"Nouveau contact",pt:"Novo contato",id:"Kontak baru",bn:"নতুন পরিচিতি"},
  "Make a copy": {de:"Kopie erstellen",ru:"Создать копию",zh:"创建副本",hi:"प्रतिलिपि बनाएं",nl:"Kopie maken",es:"Hacer una copia",ar:"إنشاء نسخة",fr:"Créer une copie",pt:"Fazer uma cópia",id:"Buat salinan",bn:"অনুলিপি তৈরি করুন"},
  "Pick colour": {de:"Farbe wählen",ru:"Выбрать цвет",zh:"选择颜色",hi:"रंग चुनें",nl:"Kleur kiezen",es:"Elegir color",ar:"اختر اللون",fr:"Choisir la couleur",pt:"Escolher cor",id:"Pilih warna",bn:"রঙ নির্বাচন করুন"},
  "Highlighter": {de:"Textmarker",ru:"Маркер",zh:"荧光笔",hi:"हाइलाइटर",nl:"Markeerstift",es:"Resaltador",ar:"قلم تحديد",fr:"Surligneur",pt:"Marca-texto",id:"Stabilo",bn:"হাইলাইটার"},
  "Pulse + HRV": {de:"Puls + HRV",ru:"Пульс + HRV",zh:"脉搏 + HRV",hi:"नाड़ी + HRV",nl:"Hartslag + HRV",es:"Pulso + HRV",ar:"النبض + HRV",fr:"Pouls + HRV",pt:"Pulso + HRV",id:"Denyut + HRV",bn:"পালস + HRV"},
  "No response.": {de:"Keine Antwort.",ru:"Нет ответа.",zh:"无响应。",hi:"कोई प्रतिक्रिया नहीं।",nl:"Geen reactie.",es:"Sin respuesta.",ar:"لا يوجد رد.",fr:"Aucune réponse.",pt:"Sem resposta.",id:"Tidak ada respons.",bn:"কোনো সাড়া নেই।"},
  "Voice typing": {de:"Spracheingabe",ru:"Голосовой ввод",zh:"语音输入",hi:"वॉइस टाइपिंग",nl:"Spraakinvoer",es:"Dictado por voz",ar:"الكتابة الصوتية",fr:"Saisie vocale",pt:"Digitação por voz",id:"Ketik dengan suara",bn:"ভয়েস টাইপিং"},
  "Pending Meds": {de:"Ausstehende Medikamente",ru:"Ожидающие лекарства",zh:"待服药物",hi:"लंबित दवाएं",nl:"Openstaande medicijnen",es:"Medicamentos pendientes",ar:"أدوية معلّقة",fr:"Médicaments en attente",pt:"Medicamentos pendentes",id:"Obat tertunda",bn:"বাকি ওষুধ"},
  "Add Manually": {de:"Manuell hinzufügen",ru:"Добавить вручную",zh:"手动添加",hi:"मैन्युअल रूप से जोड़ें",nl:"Handmatig toevoegen",es:"Añadir manualmente",ar:"إضافة يدويًا",fr:"Ajouter manuellement",pt:"Adicionar manualmente",id:"Tambah manual",bn:"ম্যানুয়ালি যোগ করুন"},
  "Repeat daily": {de:"Täglich wiederholen",ru:"Повторять ежедневно",zh:"每日重复",hi:"रोज़ दोहराएं",nl:"Dagelijks herhalen",es:"Repetir a diario",ar:"تكرار يوميًا",fr:"Répéter chaque jour",pt:"Repetir diariamente",id:"Ulangi harian",bn:"প্রতিদিন পুনরাবৃত্তি"},
  "Current plan": {de:"Aktueller Plan",ru:"Текущий план",zh:"当前套餐",hi:"वर्तमान योजना",nl:"Huidig abonnement",es:"Plan actual",ar:"الخطة الحالية",fr:"Forfait actuel",pt:"Plano atual",id:"Paket saat ini",bn:"বর্তমান প্ল্যান"},
  "Enter a code": {de:"Code eingeben",ru:"Введите код",zh:"输入代码",hi:"कोड दर्ज करें",nl:"Voer een code in",es:"Ingresa un código",ar:"أدخل رمزًا",fr:"Saisir un code",pt:"Inserir um código",id:"Masukkan kode",bn:"একটি কোড দিন"},
  "Invalid code": {de:"Ungültiger Code",ru:"Неверный код",zh:"无效代码",hi:"अमान्य कोड",nl:"Ongeldige code",es:"Código no válido",ar:"رمز غير صالح",fr:"Code invalide",pt:"Código inválido",id:"Kode tidak valid",bn:"অবৈধ কোড"},
  "Diet Program": {de:"Ernährungsplan",ru:"Программа питания",zh:"饮食计划",hi:"आहार कार्यक्रम",nl:"Dieetprogramma",es:"Programa de dieta",ar:"برنامج غذائي",fr:"Programme diététique",pt:"Programa de dieta",id:"Program diet",bn:"ডায়েট প্রোগ্রাম"},
  "Imaging type": {de:"Bildgebungstyp",ru:"Тип исследования",zh:"影像类型",hi:"इमेजिंग प्रकार",nl:"Type beeldvorming",es:"Tipo de imagen",ar:"نوع التصوير",fr:"Type d'imagerie",pt:"Tipo de imagem",id:"Jenis pencitraan",bn:"ইমেজিং ধরন"},
  "Choose files": {de:"Dateien auswählen",ru:"Выбрать файлы",zh:"选择文件",hi:"फ़ाइलें चुनें",nl:"Bestanden kiezen",es:"Elegir archivos",ar:"اختر الملفات",fr:"Choisir des fichiers",pt:"Escolher arquivos",id:"Pilih file",bn:"ফাইল নির্বাচন করুন"},
  "Water Intake": {de:"Wasseraufnahme",ru:"Потребление воды",zh:"饮水量",hi:"पानी का सेवन",nl:"Waterinname",es:"Consumo de agua",ar:"كمية الماء",fr:"Consommation d'eau",pt:"Consumo de água",id:"Asupan air",bn:"পানি গ্রহণ"},
  "Tap to start": {de:"Zum Starten tippen",ru:"Нажмите, чтобы начать",zh:"点击开始",hi:"शुरू करने के लिए टैप करें",nl:"Tik om te starten",es:"Toca para empezar",ar:"اضغط للبدء",fr:"Appuyez pour démarrer",pt:"Toque para iniciar",id:"Ketuk untuk mulai",bn:"শুরু করতে ট্যাপ করুন"},
  "Value slider": {de:"Wert-Schieberegler",ru:"Ползунок значения",zh:"数值滑块",hi:"मान स्लाइडर",nl:"Waardeschuif",es:"Control deslizante",ar:"شريط تمرير القيمة",fr:"Curseur de valeur",pt:"Controle de valor",id:"Penggeser nilai",bn:"মান স্লাইডার"},
  "Add Record": {de:"Eintrag hinzufügen",ru:"Добавить запись",zh:"添加记录",hi:"रिकॉर्ड जोड़ें",nl:"Record toevoegen",es:"Añadir registro",ar:"إضافة سجل",fr:"Ajouter un enregistrement",pt:"Adicionar registro",id:"Tambah catatan",bn:"রেকর্ড যোগ করুন"},
  "Repeat weekly": {de:"Wöchentlich wiederholen",ru:"Повторять еженедельно",zh:"每周重复",hi:"साप्ताहिक दोहराएं",nl:"Wekelijks herhalen",es:"Repetir semanalmente",ar:"تكرار أسبوعيًا",fr:"Répéter chaque semaine",pt:"Repetir semanalmente",id:"Ulangi mingguan",bn:"সাপ্তাহিক পুনরাবৃত্তি"},
  "Blood sugar": {de:"Blutzucker",ru:"Сахар в крови",zh:"血糖",hi:"रक्त शर्करा",nl:"Bloedsuiker",es:"Azúcar en sangre",ar:"سكر الدم",fr:"Glycémie",pt:"Açúcar no sangue",id:"Gula darah",bn:"রক্তে শর্করা"},
  "Heart rate": {de:"Herzfrequenz",ru:"Частота пульса",zh:"心率",hi:"हृदय गति",nl:"Hartslag",es:"Frecuencia cardíaca",ar:"معدل ضربات القلب",fr:"Fréquence cardiaque",pt:"Frequência cardíaca",id:"Detak jantung",bn:"হৃদস্পন্দন"},
  "Body temp": {de:"Körpertemperatur",ru:"Температура тела",zh:"体温",hi:"शरीर का तापमान",nl:"Lichaamstemp",es:"Temp. corporal",ar:"درجة حرارة الجسم",fr:"Température corporelle",pt:"Temp. corporal",id:"Suhu tubuh",bn:"শরীরের তাপমাত্রা"},
  "Save note": {de:"Notiz speichern",ru:"Сохранить заметку",zh:"保存笔记",hi:"नोट सहेजें",nl:"Notitie opslaan",es:"Guardar nota",ar:"حفظ الملاحظة",fr:"Enregistrer la note",pt:"Salvar nota",id:"Simpan catatan",bn:"নোট সংরক্ষণ"},
  "New note": {de:"Neue Notiz",ru:"Новая заметка",zh:"新笔记",hi:"नया नोट",nl:"Nieuwe notitie",es:"Nueva nota",ar:"ملاحظة جديدة",fr:"Nouvelle note",pt:"Nova nota",id:"Catatan baru",bn:"নতুন নোট"},
  "Reminders": {de:"Erinnerungen",ru:"Напоминания",zh:"提醒",hi:"रिमाइंडर",nl:"Herinneringen",es:"Recordatorios",ar:"التذكيرات",fr:"Rappels",pt:"Lembretes",id:"Pengingat",bn:"রিমাইন্ডার"},
  "Allergies": {de:"Allergien",ru:"Аллергии",zh:"过敏",hi:"एलर्जी",nl:"Allergieën",es:"Alergias",ar:"الحساسية",fr:"Allergies",pt:"Alergias",id:"Alergi",bn:"অ্যালার্জি"},
  "Emergency": {de:"Notfall",ru:"Экстренная помощь",zh:"紧急",hi:"आपातकाल",nl:"Noodgeval",es:"Emergencia",ar:"طوارئ",fr:"Urgence",pt:"Emergência",id:"Darurat",bn:"জরুরি"},

  // ---- Batch 4: health terms, status, actions ----
  "First Aid": {de:"Erste Hilfe",ru:"Первая помощь",zh:"急救",hi:"प्राथमिक चिकित्सा",nl:"EHBO",es:"Primeros auxilios",ar:"الإسعافات الأولية",fr:"Premiers secours",pt:"Primeiros socorros",id:"Pertolongan pertama",bn:"প্রাথমিক চিকিৎসা"},
  "Wellness": {de:"Wohlbefinden",ru:"Самочувствие",zh:"健康",hi:"वेलनेस",nl:"Welzijn",es:"Bienestar",ar:"العافية",fr:"Bien-être",pt:"Bem-estar",id:"Kesehatan",bn:"সুস্থতা"},
  "Pregnancy": {de:"Schwangerschaft",ru:"Беременность",zh:"妊娠",hi:"गर्भावस्था",nl:"Zwangerschap",es:"Embarazo",ar:"الحمل",fr:"Grossesse",pt:"Gravidez",id:"Kehamilan",bn:"গর্ভাবস্থা"},
  "Exercise": {de:"Bewegung",ru:"Упражнения",zh:"运动",hi:"व्यायाम",nl:"Beweging",es:"Ejercicio",ar:"تمرين",fr:"Exercice",pt:"Exercício",id:"Olahraga",bn:"ব্যায়াম"},
  "Breakfast": {de:"Frühstück",ru:"Завтрак",zh:"早餐",hi:"नाश्ता",nl:"Ontbijt",es:"Desayuno",ar:"الفطور",fr:"Petit-déjeuner",pt:"Café da manhã",id:"Sarapan",bn:"সকালের নাস্তা"},
  "Post-meal": {de:"Nach dem Essen",ru:"После еды",zh:"餐后",hi:"भोजन के बाद",nl:"Na de maaltijd",es:"Después de comer",ar:"بعد الأكل",fr:"Après le repas",pt:"Após a refeição",id:"Setelah makan",bn:"খাবারের পরে"},
  "Med Time": {de:"Medikamentenzeit",ru:"Время приёма",zh:"服药时间",hi:"दवा का समय",nl:"Medicijntijd",es:"Hora del medicamento",ar:"وقت الدواء",fr:"Heure du médicament",pt:"Hora do remédio",id:"Waktu obat",bn:"ওষুধের সময়"},
  "Lab value": {de:"Laborwert",ru:"Лабораторный показатель",zh:"化验值",hi:"लैब मान",nl:"Labwaarde",es:"Valor de laboratorio",ar:"قيمة مخبرية",fr:"Valeur de laboratoire",pt:"Valor laboratorial",id:"Nilai lab",bn:"ল্যাব মান"},
  "allergies": {de:"Allergien",ru:"аллергии",zh:"过敏",hi:"एलर्जी",nl:"allergieën",es:"alergias",ar:"الحساسية",fr:"allergies",pt:"alergias",id:"alergi",bn:"অ্যালার্জি"},
  "Add Meal": {de:"Mahlzeit hinzufügen",ru:"Добавить приём пищи",zh:"添加餐次",hi:"भोजन जोड़ें",nl:"Maaltijd toevoegen",es:"Añadir comida",ar:"إضافة وجبة",fr:"Ajouter un repas",pt:"Adicionar refeição",id:"Tambah makanan",bn:"খাবার যোগ করুন"},
  "Add item": {de:"Element hinzufügen",ru:"Добавить пункт",zh:"添加项目",hi:"आइटम जोड़ें",nl:"Item toevoegen",es:"Añadir elemento",ar:"إضافة عنصر",fr:"Ajouter un élément",pt:"Adicionar item",id:"Tambah item",bn:"আইটেম যোগ করুন"},
  "Add image": {de:"Bild hinzufügen",ru:"Добавить изображение",zh:"添加图片",hi:"छवि जोड़ें",nl:"Afbeelding toevoegen",es:"Añadir imagen",ar:"إضافة صورة",fr:"Ajouter une image",pt:"Adicionar imagem",id:"Tambah gambar",bn:"ছবি যোগ করুন"},
  "Log Today": {de:"Heute eintragen",ru:"Записать сегодня",zh:"记录今天",hi:"आज दर्ज करें",nl:"Vandaag loggen",es:"Registrar hoy",ar:"تسجيل اليوم",fr:"Enregistrer aujourd'hui",pt:"Registrar hoje",id:"Catat hari ini",bn:"আজ লগ করুন"},
  "Next Appt": {de:"Nächster Termin",ru:"Следующий приём",zh:"下次预约",hi:"अगली मुलाकात",nl:"Volgende afspraak",es:"Próxima cita",ar:"الموعد التالي",fr:"Prochain rendez-vous",pt:"Próxima consulta",id:"Janji berikutnya",bn:"পরবর্তী অ্যাপয়েন্টমেন্ট"},
  "Continue": {de:"Weiter",ru:"Продолжить",zh:"继续",hi:"जारी रखें",nl:"Doorgaan",es:"Continuar",ar:"متابعة",fr:"Continuer",pt:"Continuar",id:"Lanjutkan",bn:"চালিয়ে যান"},
  "Loading…": {de:"Wird geladen…",ru:"Загрузка…",zh:"加载中…",hi:"लोड हो रहा है…",nl:"Laden…",es:"Cargando…",ar:"جارٍ التحميل…",fr:"Chargement…",pt:"Carregando…",id:"Memuat…",bn:"লোড হচ্ছে…"},
  "just now": {de:"gerade eben",ru:"только что",zh:"刚刚",hi:"अभी अभी",nl:"zojuist",es:"ahora mismo",ar:"الآن",fr:"à l'instant",pt:"agora mesmo",id:"baru saja",bn:"এইমাত্র"},
  "days left": {de:"Tage übrig",ru:"дней осталось",zh:"天剩余",hi:"दिन बाकी",nl:"dagen over",es:"días restantes",ar:"يوم متبقٍ",fr:"jours restants",pt:"dias restantes",id:"hari lagi",bn:"দিন বাকি"},
  "Last sync": {de:"Letzte Sync",ru:"Последняя синхронизация",zh:"上次同步",hi:"पिछला सिंक",nl:"Laatste sync",es:"Última sincronización",ar:"آخر مزامنة",fr:"Dernière sync",pt:"Última sincronização",id:"Sinkron terakhir",bn:"শেষ সিঙ্ক"},
  "Box count": {de:"Packungsanzahl",ru:"Кол-во упаковок",zh:"盒数",hi:"बॉक्स गिनती",nl:"Aantal dozen",es:"N.º de cajas",ar:"عدد العلب",fr:"Nombre de boîtes",pt:"Contagem de caixas",id:"Jumlah kotak",bn:"বাক্সের সংখ্যা"},
  "App Lock": {de:"App-Sperre",ru:"Блокировка приложения",zh:"应用锁",hi:"ऐप लॉक",nl:"App-vergrendeling",es:"Bloqueo de app",ar:"قفل التطبيق",fr:"Verrou de l'app",pt:"Bloqueio do app",id:"Kunci aplikasi",bn:"অ্যাপ লক"},
  "Lock now": {de:"Jetzt sperren",ru:"Заблокировать",zh:"立即锁定",hi:"अभी लॉक करें",nl:"Nu vergrendelen",es:"Bloquear ahora",ar:"اقفل الآن",fr:"Verrouiller maintenant",pt:"Bloquear agora",id:"Kunci sekarang",bn:"এখন লক করুন"},
  "SMS code": {de:"SMS-Code",ru:"SMS-код",zh:"短信验证码",hi:"एसएमएस कोड",nl:"Sms-code",es:"Código SMS",ar:"رمز الرسالة",fr:"Code SMS",pt:"Código SMS",id:"Kode SMS",bn:"এসএমএস কোড"},
  "Interpret": {de:"Auswerten",ru:"Расшифровать",zh:"解读",hi:"व्याख्या करें",nl:"Interpreteren",es:"Interpretar",ar:"تفسير",fr:"Interpréter",pt:"Interpretar",id:"Tafsirkan",bn:"ব্যাখ্যা করুন"},
  "Estimated": {de:"Geschätzt",ru:"Оценочно",zh:"估算",hi:"अनुमानित",nl:"Geschat",es:"Estimado",ar:"تقديري",fr:"Estimé",pt:"Estimado",id:"Perkiraan",bn:"আনুমানিক"},
  "Clear All": {de:"Alles löschen",ru:"Очистить все",zh:"清除全部",hi:"सभी साफ़ करें",nl:"Alles wissen",es:"Borrar todo",ar:"مسح الكل",fr:"Tout effacer",pt:"Limpar tudo",id:"Hapus semua",bn:"সব সাফ করুন"},
  "Clear all": {de:"Alles löschen",ru:"Очистить все",zh:"清除全部",hi:"सभी साफ़ करें",nl:"Alles wissen",es:"Borrar todo",ar:"مسح الكل",fr:"Tout effacer",pt:"Limpar tudo",id:"Hapus semua",bn:"সব সাফ করুন"},
  "Recording": {de:"Aufnahme",ru:"Запись",zh:"录制中",hi:"रिकॉर्डिंग",nl:"Opnemen",es:"Grabando",ar:"جارٍ التسجيل",fr:"Enregistrement",pt:"Gravando",id:"Merekam",bn:"রেকর্ডিং"},
  "Zoom out": {de:"Verkleinern",ru:"Уменьшить",zh:"缩小",hi:"ज़ूम आउट",nl:"Uitzoomen",es:"Alejar",ar:"تصغير",fr:"Dézoomer",pt:"Reduzir zoom",id:"Perkecil",bn:"জুম আউট"},
  "Thin pen": {de:"Dünner Stift",ru:"Тонкое перо",zh:"细笔",hi:"पतली कलम",nl:"Dunne pen",es:"Lápiz fino",ar:"قلم رفيع",fr:"Stylo fin",pt:"Caneta fina",id:"Pena tipis",bn:"সরু কলম"},
  "Moderate": {de:"Mäßig",ru:"Умеренно",zh:"中等",hi:"मध्यम",nl:"Matig",es:"Moderado",ar:"معتدل",fr:"Modéré",pt:"Moderado",id:"Sedang",bn:"মাঝারি"},
  "Very Bad": {de:"Sehr schlecht",ru:"Очень плохо",zh:"很差",hi:"बहुत बुरा",nl:"Heel slecht",es:"Muy mal",ar:"سيئ جدًا",fr:"Très mauvais",pt:"Muito ruim",id:"Sangat buruk",bn:"খুব খারাপ"},
  "excellent": {de:"ausgezeichnet",ru:"отлично",zh:"极好",hi:"उत्कृष्ट",nl:"uitstekend",es:"excelente",ar:"ممتاز",fr:"excellent",pt:"excelente",id:"sangat baik",bn:"চমৎকার"},
  "Excellent": {de:"Ausgezeichnet",ru:"Отлично",zh:"极好",hi:"उत्कृष्ट",nl:"Uitstekend",es:"Excelente",ar:"ممتاز",fr:"Excellent",pt:"Excelente",id:"Sangat baik",bn:"চমৎকার"},
  "Report →": {de:"Bericht →",ru:"Отчёт →",zh:"报告 →",hi:"रिपोर्ट →",nl:"Rapport →",es:"Informe →",ar:"التقرير →",fr:"Rapport →",pt:"Relatório →",id:"Laporan →",bn:"রিপোর্ট →"},
  "Contacts": {de:"Kontakte",ru:"Контакты",zh:"联系人",hi:"संपर्क",nl:"Contacten",es:"Contactos",ar:"جهات الاتصال",fr:"Contacts",pt:"Contatos",id:"Kontak",bn:"পরিচিতি"},

  // ---- Batch 5: common nouns & actions ----
  "Weight": {de:"Gewicht",ru:"Вес",zh:"体重",hi:"वजन",nl:"Gewicht",es:"Peso",ar:"الوزن",fr:"Poids",pt:"Peso",id:"Berat",bn:"ওজন"},
  "Camera": {de:"Kamera",ru:"Камера",zh:"相机",hi:"कैमरा",nl:"Camera",es:"Cámara",ar:"الكاميرا",fr:"Appareil photo",pt:"Câmera",id:"Kamera",bn:"ক্যামেরা"},
  "Glucose": {de:"Glukose",ru:"Глюкоза",zh:"血糖",hi:"ग्लूकोज",nl:"Glucose",es:"Glucosa",ar:"الجلوكوز",fr:"Glucose",pt:"Glicose",id:"Glukosa",bn:"গ্লুকোজ"},
  "Doctor": {de:"Arzt",ru:"Врач",zh:"医生",hi:"डॉक्टर",nl:"Dokter",es:"Médico",ar:"الطبيب",fr:"Médecin",pt:"Médico",id:"Dokter",bn:"ডাক্তার"},
  "Compass": {de:"Kompass",ru:"Компас",zh:"指南针",hi:"कम्पास",nl:"Kompas",es:"Brújula",ar:"البوصلة",fr:"Boussole",pt:"Bússola",id:"Kompas",bn:"কম্পাস"},
  "Weather": {de:"Wetter",ru:"Погода",zh:"天气",hi:"मौसम",nl:"Weer",es:"Clima",ar:"الطقس",fr:"Météo",pt:"Clima",id:"Cuaca",bn:"আবহাওয়া"},
  "Barcode": {de:"Strichcode",ru:"Штрих-код",zh:"条形码",hi:"बारकोड",nl:"Streepjescode",es:"Código de barras",ar:"الباركود",fr:"Code-barres",pt:"Código de barras",id:"Kode batang",bn:"বারকোড"},
  "Female": {de:"Weiblich",ru:"Женский",zh:"女",hi:"महिला",nl:"Vrouw",es:"Mujer",ar:"أنثى",fr:"Femme",pt:"Feminino",id:"Wanita",bn:"মহিলা"},
  "Delete": {de:"Löschen",ru:"Удалить",zh:"删除",hi:"हटाएं",nl:"Verwijderen",es:"Eliminar",ar:"حذف",fr:"Supprimer",pt:"Excluir",id:"Hapus",bn:"মুছুন"},
  "Search": {de:"Suchen",ru:"Поиск",zh:"搜索",hi:"खोजें",nl:"Zoeken",es:"Buscar",ar:"بحث",fr:"Rechercher",pt:"Buscar",id:"Cari",bn:"অনুসন্ধান"},
  "Remove": {de:"Entfernen",ru:"Убрать",zh:"移除",hi:"हटाएं",nl:"Verwijderen",es:"Quitar",ar:"إزالة",fr:"Retirer",pt:"Remover",id:"Hapus",bn:"সরান"},
  "Create": {de:"Erstellen",ru:"Создать",zh:"创建",hi:"बनाएं",nl:"Aanmaken",es:"Crear",ar:"إنشاء",fr:"Créer",pt:"Criar",id:"Buat",bn:"তৈরি করুন"},
  "Unlock": {de:"Entsperren",ru:"Разблокировать",zh:"解锁",hi:"अनलॉक करें",nl:"Ontgrendelen",es:"Desbloquear",ar:"فتح القفل",fr:"Déverrouiller",pt:"Desbloquear",id:"Buka kunci",bn:"আনলক"},
  "Cancel": {de:"Abbrechen",ru:"Отмена",zh:"取消",hi:"रद्द करें",nl:"Annuleren",es:"Cancelar",ar:"إلغاء",fr:"Annuler",pt:"Cancelar",id:"Batal",bn:"বাতিল"},
  "Export": {de:"Exportieren",ru:"Экспорт",zh:"导出",hi:"निर्यात",nl:"Exporteren",es:"Exportar",ar:"تصدير",fr:"Exporter",pt:"Exportar",id:"Ekspor",bn:"এক্সপোর্ট"},
  "Import": {de:"Importieren",ru:"Импорт",zh:"导入",hi:"आयात",nl:"Importeren",es:"Importar",ar:"استيراد",fr:"Importer",pt:"Importar",id:"Impor",bn:"ইমপোর্ট"},
  "Device": {de:"Gerät",ru:"Устройство",zh:"设备",hi:"डिवाइस",nl:"Apparaat",es:"Dispositivo",ar:"الجهاز",fr:"Appareil",pt:"Dispositivo",id:"Perangkat",bn:"ডিভাইস"},
  "Normal": {de:"Normal",ru:"Норма",zh:"正常",hi:"सामान्य",nl:"Normaal",es:"Normal",ar:"طبيعي",fr:"Normal",pt:"Normal",id:"Normal",bn:"স্বাভাবিক"},
  "Status": {de:"Status",ru:"Статус",zh:"状态",hi:"स्थिति",nl:"Status",es:"Estado",ar:"الحالة",fr:"Statut",pt:"Status",id:"Status",bn:"অবস্থা"},
  "Change": {de:"Ändern",ru:"Изменить",zh:"更改",hi:"बदलें",nl:"Wijzigen",es:"Cambiar",ar:"تغيير",fr:"Modifier",pt:"Alterar",id:"Ubah",bn:"পরিবর্তন"},
  "Latest": {de:"Neueste",ru:"Последние",zh:"最新",hi:"नवीनतम",nl:"Nieuwste",es:"Más reciente",ar:"الأحدث",fr:"Dernier",pt:"Mais recente",id:"Terbaru",bn:"সর্বশেষ"},
  "Random": {de:"Zufällig",ru:"Случайно",zh:"随机",hi:"यादृच्छिक",nl:"Willekeurig",es:"Aleatorio",ar:"عشوائي",fr:"Aléatoire",pt:"Aleatório",id:"Acak",bn:"এলোমেলো"},
  "Toggle": {de:"Umschalten",ru:"Переключить",zh:"切换",hi:"टॉगल",nl:"Wisselen",es:"Alternar",ar:"تبديل",fr:"Basculer",pt:"Alternar",id:"Alihkan",bn:"টগল"},
  "Set up": {de:"Einrichten",ru:"Настроить",zh:"设置",hi:"सेट अप करें",nl:"Instellen",es:"Configurar",ar:"إعداد",fr:"Configurer",pt:"Configurar",id:"Siapkan",bn:"সেটআপ"},
  "Groups": {de:"Gruppen",ru:"Группы",zh:"群组",hi:"समूह",nl:"Groepen",es:"Grupos",ar:"المجموعات",fr:"Groupes",pt:"Grupos",id:"Grup",bn:"গ্রুপ"},
  "Report": {de:"Bericht",ru:"Отчёт",zh:"报告",hi:"रिपोर्ट",nl:"Rapport",es:"Informe",ar:"تقرير",fr:"Rapport",pt:"Relatório",id:"Laporan",bn:"রিপোর্ট"},
  "Labels": {de:"Etiketten",ru:"Метки",zh:"标签",hi:"लेबल",nl:"Labels",es:"Etiquetas",ar:"التسميات",fr:"Étiquettes",pt:"Etiquetas",id:"Label",bn:"লেবেল"},
  "Colour": {de:"Farbe",ru:"Цвет",zh:"颜色",hi:"रंग",nl:"Kleur",es:"Color",ar:"اللون",fr:"Couleur",pt:"Cor",id:"Warna",bn:"রঙ"},
  "Eraser": {de:"Radierer",ru:"Ластик",zh:"橡皮擦",hi:"रबड़",nl:"Gum",es:"Borrador",ar:"ممحاة",fr:"Gomme",pt:"Borracha",id:"Penghapus",bn:"রাবার"},
  "Marker": {de:"Marker",ru:"Маркер",zh:"记号笔",hi:"मार्कर",nl:"Marker",es:"Marcador",ar:"قلم",fr:"Marqueur",pt:"Marcador",id:"Spidol",bn:"মার্কার"},
  "Got it": {de:"Verstanden",ru:"Понятно",zh:"知道了",hi:"समझ गया",nl:"Begrepen",es:"Entendido",ar:"فهمت",fr:"Compris",pt:"Entendi",id:"Mengerti",bn:"বুঝেছি"},
  "chronic": {de:"chronisch",ru:"хронический",zh:"慢性",hi:"पुरानी",nl:"chronisch",es:"crónico",ar:"مزمن",fr:"chronique",pt:"crônico",id:"kronis",bn:"দীর্ঘস্থায়ী"},
  "pending": {de:"ausstehend",ru:"ожидает",zh:"待处理",hi:"लंबित",nl:"in behandeling",es:"pendiente",ar:"معلّق",fr:"en attente",pt:"pendente",id:"tertunda",bn:"বাকি"},
  "Per day": {de:"Pro Tag",ru:"В день",zh:"每天",hi:"प्रति दिन",nl:"Per dag",es:"Por día",ar:"يوميًا",fr:"Par jour",pt:"Por dia",id:"Per hari",bn:"প্রতিদিন"},
  "edited": {de:"bearbeitet",ru:"изменено",zh:"已编辑",hi:"संपादित",nl:"bewerkt",es:"editado",ar:"مُعدّل",fr:"modifié",pt:"editado",id:"diedit",bn:"সম্পাদিত"},
  "⏹ Stop": {de:"⏹ Stopp",ru:"⏹ Стоп",zh:"⏹ 停止",hi:"⏹ रोकें",nl:"⏹ Stop",es:"⏹ Detener",ar:"⏹ إيقاف",fr:"⏹ Arrêter",pt:"⏹ Parar",id:"⏹ Berhenti",bn:"⏹ থামুন"},
  "ALERTS": {de:"WARNUNGEN",ru:"ОПОВЕЩЕНИЯ",zh:"提醒",hi:"अलर्ट",nl:"WAARSCHUWINGEN",es:"ALERTAS",ar:"تنبيهات",fr:"ALERTES",pt:"ALERTAS",id:"PERINGATAN",bn:"সতর্কতা"},
  "Doctors": {de:"Ärzte",ru:"Врачи",zh:"医生",hi:"डॉक्टर",nl:"Artsen",es:"Médicos",ar:"الأطباء",fr:"Médecins",pt:"Médicos",id:"Dokter",bn:"ডাক্তার"},
  "Pharmacy": {de:"Apotheke",ru:"Аптека",zh:"药房",hi:"फार्मेसी",nl:"Apotheek",es:"Farmacia",ar:"صيدلية",fr:"Pharmacie",pt:"Farmácia",id:"Apotek",bn:"ফার্মেসি"},
  "Symptoms": {de:"Symptome",ru:"Симптомы",zh:"症状",hi:"लक्षण",nl:"Symptomen",es:"Síntomas",ar:"الأعراض",fr:"Symptômes",pt:"Sintomas",id:"Gejala",bn:"উপসর্গ"},

  // ---- Batch 6: readable phrases (health, dialogs, actions) ----
  "Blood Glucose": {de:"Blutzucker",ru:"Глюкоза крови",zh:"血糖",hi:"रक्त ग्लूकोज",nl:"Bloedglucose",es:"Glucosa en sangre",ar:"سكر الدم",fr:"Glycémie",pt:"Glicemia",id:"Glukosa darah",bn:"রক্তে গ্লুকোজ"},
  "Last Glucose": {de:"Letzter Glukosewert",ru:"Последняя глюкоза",zh:"最近血糖",hi:"अंतिम ग्लूकोज",nl:"Laatste glucose",es:"Última glucosa",ar:"آخر قياس سكر",fr:"Dernière glycémie",pt:"Última glicemia",id:"Glukosa terakhir",bn:"সর্বশেষ গ্লুকোজ"},
  "Medical image": {de:"Medizinisches Bild",ru:"Медицинский снимок",zh:"医学影像",hi:"चिकित्सा छवि",nl:"Medisch beeld",es:"Imagen médica",ar:"صورة طبية",fr:"Image médicale",pt:"Imagem médica",id:"Citra medis",bn:"চিকিৎসা চিত্র"},
  "Measure pulse": {de:"Puls messen",ru:"Измерить пульс",zh:"测量脉搏",hi:"नाड़ी मापें",nl:"Hartslag meten",es:"Medir pulso",ar:"قياس النبض",fr:"Mesurer le pouls",pt:"Medir pulso",id:"Ukur denyut",bn:"পালস মাপুন"},
  "Measure again": {de:"Erneut messen",ru:"Измерить снова",zh:"重新测量",hi:"फिर से मापें",nl:"Opnieuw meten",es:"Medir de nuevo",ar:"قياس مرة أخرى",fr:"Mesurer à nouveau",pt:"Medir novamente",id:"Ukur lagi",bn:"আবার মাপুন"},
  "balance test": {de:"Gleichgewichtstest",ru:"тест равновесия",zh:"平衡测试",hi:"संतुलन परीक्षण",nl:"balanstest",es:"prueba de equilibrio",ar:"اختبار التوازن",fr:"test d'équilibre",pt:"teste de equilíbrio",id:"tes keseimbangan",bn:"ভারসাম্য পরীক্ষা"},
  "reaction test": {de:"Reaktionstest",ru:"тест реакции",zh:"反应测试",hi:"प्रतिक्रिया परीक्षण",nl:"reactietest",es:"prueba de reacción",ar:"اختبار رد الفعل",fr:"test de réaction",pt:"teste de reação",id:"tes reaksi",bn:"প্রতিক্রিয়া পরীক্ষা"},
  "Accessibility": {de:"Barrierefreiheit",ru:"Доступность",zh:"无障碍",hi:"सुलभता",nl:"Toegankelijkheid",es:"Accesibilidad",ar:"إمكانية الوصول",fr:"Accessibilité",pt:"Acessibilidade",id:"Aksesibilitas",bn:"অ্যাক্সেসযোগ্যতা"},
  "Phone Number": {de:"Telefonnummer",ru:"Номер телефона",zh:"电话号码",hi:"फ़ोन नंबर",nl:"Telefoonnummer",es:"Número de teléfono",ar:"رقم الهاتف",fr:"Numéro de téléphone",pt:"Número de telefone",id:"Nomor telepon",bn:"ফোন নম্বর"},
  "Create Group": {de:"Gruppe erstellen",ru:"Создать группу",zh:"创建群组",hi:"समूह बनाएं",nl:"Groep aanmaken",es:"Crear grupo",ar:"إنشاء مجموعة",fr:"Créer un groupe",pt:"Criar grupo",id:"Buat grup",bn:"গ্রুপ তৈরি করুন"},
  "Edit Contact": {de:"Kontakt bearbeiten",ru:"Изменить контакт",zh:"编辑联系人",hi:"संपर्क संपादित करें",nl:"Contact bewerken",es:"Editar contacto",ar:"تعديل جهة الاتصال",fr:"Modifier le contact",pt:"Editar contato",id:"Ubah kontak",bn:"পরিচিতি সম্পাদনা"},
  "Search place": {de:"Ort suchen",ru:"Найти место",zh:"搜索地点",hi:"स्थान खोजें",nl:"Plaats zoeken",es:"Buscar lugar",ar:"البحث عن مكان",fr:"Rechercher un lieu",pt:"Buscar local",id:"Cari tempat",bn:"স্থান খুঁজুন"},
  "Enter text...": {de:"Text eingeben…",ru:"Введите текст…",zh:"输入文本…",hi:"टेक्स्ट दर्ज करें…",nl:"Tekst invoeren…",es:"Escribe texto…",ar:"أدخل النص…",fr:"Saisir du texte…",pt:"Digite o texto…",id:"Masukkan teks…",bn:"টেক্সট লিখুন…"},
  "Identity Info": {de:"Identitätsdaten",ru:"Личные данные",zh:"身份信息",hi:"पहचान जानकारी",nl:"Identiteitsgegevens",es:"Datos de identidad",ar:"معلومات الهوية",fr:"Informations d'identité",pt:"Dados de identidade",id:"Info identitas",bn:"পরিচয় তথ্য"},
  "Edit message:": {de:"Nachricht bearbeiten:",ru:"Изменить сообщение:",zh:"编辑消息：",hi:"संदेश संपादित करें:",nl:"Bericht bewerken:",es:"Editar mensaje:",ar:"تعديل الرسالة:",fr:"Modifier le message :",pt:"Editar mensagem:",id:"Ubah pesan:",bn:"বার্তা সম্পাদনা:"},
  "Mark all read": {de:"Alle als gelesen",ru:"Отметить прочитанным",zh:"全部标为已读",hi:"सभी पढ़ा हुआ",nl:"Alles als gelezen",es:"Marcar todo leído",ar:"تحديد الكل كمقروء",fr:"Tout marquer comme lu",pt:"Marcar tudo como lido",id:"Tandai semua dibaca",bn:"সব পঠিত"},
  "Swap languages": {de:"Sprachen tauschen",ru:"Поменять языки",zh:"交换语言",hi:"भाषाएं बदलें",nl:"Talen wisselen",es:"Intercambiar idiomas",ar:"تبديل اللغتين",fr:"Inverser les langues",pt:"Trocar idiomas",id:"Tukar bahasa",bn:"ভাষা অদলবদল"},
  "Translating...": {de:"Wird übersetzt…",ru:"Перевод…",zh:"翻译中…",hi:"अनुवाद हो रहा है…",nl:"Vertalen…",es:"Traduciendo…",ar:"جارٍ الترجمة…",fr:"Traduction…",pt:"Traduzindo…",id:"Menerjemahkan…",bn:"অনুবাদ হচ্ছে…"},
  "Daily Progress": {de:"Täglicher Fortschritt",ru:"Прогресс за день",zh:"每日进度",hi:"दैनिक प्रगति",nl:"Dagelijkse voortgang",es:"Progreso diario",ar:"التقدم اليومي",fr:"Progrès quotidien",pt:"Progresso diário",id:"Kemajuan harian",bn:"দৈনিক অগ্রগতি"},
  "Moved to Trash": {de:"In den Papierkorb verschoben",ru:"Перемещено в корзину",zh:"已移至回收站",hi:"ट्रैश में ले जाया गया",nl:"Naar prullenbak verplaatst",es:"Movido a la papelera",ar:"نُقل إلى المهملات",fr:"Déplacé vers la corbeille",pt:"Movido para a lixeira",id:"Dipindahkan ke sampah",bn:"ট্র্যাশে সরানো হয়েছে"},
  "Not connected": {de:"Nicht verbunden",ru:"Не подключено",zh:"未连接",hi:"कनेक्ट नहीं है",nl:"Niet verbonden",es:"No conectado",ar:"غير متصل",fr:"Non connecté",pt:"Não conectado",id:"Tidak terhubung",bn:"সংযুক্ত নয়"},
  "This session": {de:"Diese Sitzung",ru:"Эта сессия",zh:"本次会话",hi:"यह सत्र",nl:"Deze sessie",es:"Esta sesión",ar:"هذه الجلسة",fr:"Cette session",pt:"Esta sessão",id:"Sesi ini",bn:"এই সেশন"},
  "Drawing note": {de:"Zeichennotiz",ru:"Заметка-рисунок",zh:"绘图笔记",hi:"ड्रॉइंग नोट",nl:"Tekennotitie",es:"Nota de dibujo",ar:"ملاحظة رسم",fr:"Note dessinée",pt:"Nota de desenho",id:"Catatan gambar",bn:"অঙ্কন নোট"},
  "Collaborator": {de:"Mitarbeiter",ru:"Участник",zh:"协作者",hi:"सहयोगी",nl:"Medewerker",es:"Colaborador",ar:"متعاون",fr:"Collaborateur",pt:"Colaborador",id:"Kolaborator",bn:"সহযোগী"},
  "WhatsApp code": {de:"WhatsApp-Code",ru:"Код WhatsApp",zh:"WhatsApp 验证码",hi:"व्हाट्सएप कोड",nl:"WhatsApp-code",es:"Código de WhatsApp",ar:"رمز واتساب",fr:"Code WhatsApp",pt:"Código do WhatsApp",id:"Kode WhatsApp",bn:"হোয়াটসঅ্যাপ কোড"},
  "Open e-Nabız": {de:"e-Nabız öffnen",ru:"Открыть e-Nabız",zh:"打开 e-Nabız",hi:"e-Nabız खोलें",nl:"e-Nabız openen",es:"Abrir e-Nabız",ar:"فتح e-Nabız",fr:"Ouvrir e-Nabız",pt:"Abrir e-Nabız",id:"Buka e-Nabız",bn:"e-Nabız খুলুন"},
  "What to eat…": {de:"Was essen…",ru:"Что съесть…",zh:"吃什么…",hi:"क्या खाएं…",nl:"Wat eten…",es:"Qué comer…",ar:"ماذا آكل…",fr:"Que manger…",pt:"O que comer…",id:"Makan apa…",bn:"কী খাবেন…"},
  "Stand still…": {de:"Still stehen…",ru:"Стойте спокойно…",zh:"保持静止…",hi:"स्थिर रहें…",nl:"Sta stil…",es:"Quédate quieto…",ar:"قف بلا حركة…",fr:"Restez immobile…",pt:"Fique parado…",id:"Diam di tempat…",bn:"স্থির থাকুন…"},
  "Hourly (24h)": {de:"Stündlich (24h)",ru:"Ежечасно (24ч)",zh:"每小时 (24h)",hi:"हर घंटे (24घं)",nl:"Per uur (24u)",es:"Cada hora (24h)",ar:"كل ساعة (24س)",fr:"Horaire (24h)",pt:"A cada hora (24h)",id:"Per jam (24j)",bn:"ঘণ্টায় (২৪ঘ)"},
  "7-Day (weekly)": {de:"7 Tage (wöchentlich)",ru:"7 дней (неделя)",zh:"7天 (每周)",hi:"7 दिन (साप्ताहिक)",nl:"7 dagen (wekelijks)",es:"7 días (semanal)",ar:"7 أيام (أسبوعي)",fr:"7 jours (hebdo)",pt:"7 dias (semanal)",id:"7 hari (mingguan)",bn:"৭ দিন (সাপ্তাহিক)"},
  "system default": {de:"Systemstandard",ru:"по умолчанию",zh:"系统默认",hi:"सिस्टम डिफ़ॉल्ट",nl:"systeemstandaard",es:"predeterminado del sistema",ar:"افتراضي النظام",fr:"par défaut du système",pt:"padrão do sistema",id:"bawaan sistem",bn:"সিস্টেম ডিফল্ট"},
  "added as note": {de:"als Notiz hinzugefügt",ru:"добавлено как заметка",zh:"已添加为笔记",hi:"नोट के रूप में जोड़ा गया",nl:"toegevoegd als notitie",es:"añadido como nota",ar:"أُضيف كملاحظة",fr:"ajouté comme note",pt:"adicionado como nota",id:"ditambahkan sebagai catatan",bn:"নোট হিসেবে যোগ হয়েছে"},
  "Poison line": {de:"Vergiftungs-Hotline",ru:"Токсикологическая линия",zh:"中毒热线",hi:"ज़हर हेल्पलाइन",nl:"Vergiftigingslijn",es:"Línea de toxicología",ar:"خط التسمم",fr:"Centre antipoison",pt:"Linha de intoxicação",id:"Saluran keracunan",bn:"বিষক্রিয়া হেল্পলাইন"},
  "Notifications": {de:"Benachrichtigungen",ru:"Уведомления",zh:"通知",hi:"सूचनाएं",nl:"Meldingen",es:"Notificaciones",ar:"الإشعارات",fr:"Notifications",pt:"Notificações",id:"Notifikasi",bn:"বিজ্ঞপ্তি"},
  "Appointment": {de:"Termin",ru:"Приём",zh:"预约",hi:"अपॉइंटमेंट",nl:"Afspraak",es:"Cita",ar:"موعد",fr:"Rendez-vous",pt:"Consulta",id:"Janji temu",bn:"অ্যাপয়েন্টমেন্ট"},
  "Medication": {de:"Medikament",ru:"Лекарство",zh:"药物",hi:"दवा",nl:"Medicijn",es:"Medicamento",ar:"دواء",fr:"Médicament",pt:"Medicamento",id:"Obat",bn:"ওষুধ"},

  // ---- Batch 7: readable phrases (medical, settings, status) ----
  "Medical Records": {de:"Medizinische Unterlagen",ru:"Медицинские записи",zh:"病历",hi:"चिकित्सा रिकॉर्ड",nl:"Medische dossiers",es:"Historial médico",ar:"السجلات الطبية",fr:"Dossiers médicaux",pt:"Registros médicos",id:"Rekam medis",bn:"চিকিৎসা রেকর্ড"},
  "Biological Sex": {de:"Biologisches Geschlecht",ru:"Биологический пол",zh:"生理性别",hi:"जैविक लिंग",nl:"Biologisch geslacht",es:"Sexo biológico",ar:"الجنس البيولوجي",fr:"Sexe biologique",pt:"Sexo biológico",id:"Jenis kelamin biologis",bn:"জৈবিক লিঙ্গ"},
  "On anticoagulant": {de:"Nimmt Blutverdünner",ru:"Принимает антикоагулянт",zh:"服用抗凝血药",hi:"एंटीकोआगुलेंट पर",nl:"Gebruikt bloedverdunner",es:"Con anticoagulante",ar:"يتناول مضاد تخثر",fr:"Sous anticoagulant",pt:"Em anticoagulante",id:"Menggunakan antikoagulan",bn:"অ্যান্টিকোয়াগুল্যান্টে"},
  "CRITICAL GLUCOSE": {de:"KRITISCHER BLUTZUCKER",ru:"КРИТИЧЕСКАЯ ГЛЮКОЗА",zh:"血糖危急",hi:"गंभीर ग्लूकोज",nl:"KRITIEKE GLUCOSE",es:"GLUCOSA CRÍTICA",ar:"سكر حرج",fr:"GLYCÉMIE CRITIQUE",pt:"GLICEMIA CRÍTICA",id:"GLUKOSA KRITIS",bn:"সংকটজনক গ্লুকোজ"},
  "Balance / Gait": {de:"Gleichgewicht / Gang",ru:"Равновесие / Походка",zh:"平衡 / 步态",hi:"संतुलन / चाल",nl:"Balans / Gang",es:"Equilibrio / Marcha",ar:"التوازن / المشية",fr:"Équilibre / Démarche",pt:"Equilíbrio / Marcha",id:"Keseimbangan / Gaya jalan",bn:"ভারসাম্য / চলন"},
  "Post-meal (2h)": {de:"Nach dem Essen (2 Std.)",ru:"После еды (2ч)",zh:"餐后 (2小时)",hi:"भोजन के बाद (2घं)",nl:"Na de maaltijd (2u)",es:"Después de comer (2h)",ar:"بعد الأكل (ساعتان)",fr:"Après le repas (2h)",pt:"Após a refeição (2h)",id:"Setelah makan (2j)",bn:"খাবারের ২ঘ পরে"},
  "Signal quality": {de:"Signalqualität",ru:"Качество сигнала",zh:"信号质量",hi:"सिग्नल गुणवत्ता",nl:"Signaalkwaliteit",es:"Calidad de la señal",ar:"جودة الإشارة",fr:"Qualité du signal",pt:"Qualidade do sinal",id:"Kualitas sinyal",bn:"সিগন্যাল মান"},
  "Drug recognized": {de:"Medikament erkannt",ru:"Лекарство распознано",zh:"已识别药物",hi:"दवा पहचानी गई",nl:"Medicijn herkend",es:"Medicamento reconocido",ar:"تم التعرف على الدواء",fr:"Médicament reconnu",pt:"Medicamento reconhecido",id:"Obat dikenali",bn:"ওষুধ শনাক্ত হয়েছে"},
  "Emergency Phone": {de:"Notfalltelefon",ru:"Экстренный телефон",zh:"紧急电话",hi:"आपातकालीन फोन",nl:"Noodtelefoon",es:"Teléfono de emergencia",ar:"هاتف الطوارئ",fr:"Téléphone d'urgence",pt:"Telefone de emergência",id:"Telepon darurat",bn:"জরুরি ফোন"},
  "Health Reminders": {de:"Gesundheitserinnerungen",ru:"Напоминания о здоровье",zh:"健康提醒",hi:"स्वास्थ्य रिमाइंडर",nl:"Gezondheidsherinneringen",es:"Recordatorios de salud",ar:"تذكيرات صحية",fr:"Rappels santé",pt:"Lembretes de saúde",id:"Pengingat kesehatan",bn:"স্বাস্থ্য রিমাইন্ডার"},
  "Wellness Bonus": {de:"Wohlfühl-Bonus",ru:"Бонус за самочувствие",zh:"健康加分",hi:"वेलनेस बोनस",nl:"Welzijnsbonus",es:"Bono de bienestar",ar:"مكافأة العافية",fr:"Bonus bien-être",pt:"Bônus de bem-estar",id:"Bonus kesehatan",bn:"সুস্থতা বোনাস"},
  "Reaction / Focus": {de:"Reaktion / Fokus",ru:"Реакция / Внимание",zh:"反应 / 专注",hi:"प्रतिक्रिया / फोकस",nl:"Reactie / Focus",es:"Reacción / Enfoque",ar:"رد الفعل / التركيز",fr:"Réaction / Concentration",pt:"Reação / Foco",id:"Reaksi / Fokus",bn:"প্রতিক্রিয়া / মনোযোগ"},
  "average reaction": {de:"durchschnittliche Reaktion",ru:"средняя реакция",zh:"平均反应",hi:"औसत प्रतिक्रिया",nl:"gemiddelde reactie",es:"reacción media",ar:"متوسط رد الفعل",fr:"réaction moyenne",pt:"reação média",id:"reaksi rata-rata",bn:"গড় প্রতিক্রিয়া"},
  "Content Filter": {de:"Inhaltsfilter",ru:"Фильтр контента",zh:"内容过滤",hi:"सामग्री फ़िल्टर",nl:"Inhoudsfilter",es:"Filtro de contenido",ar:"مرشح المحتوى",fr:"Filtre de contenu",pt:"Filtro de conteúdo",id:"Filter konten",bn:"কন্টেন্ট ফিল্টার"},
  "Voice guidance": {de:"Sprachführung",ru:"Голосовые подсказки",zh:"语音引导",hi:"वॉइस मार्गदर्शन",nl:"Spraakbegeleiding",es:"Guía por voz",ar:"إرشاد صوتي",fr:"Guidage vocal",pt:"Orientação por voz",id:"Panduan suara",bn:"ভয়েস গাইড"},
  "Email or phone": {de:"E-Mail oder Telefon",ru:"Эл. почта или телефон",zh:"邮箱或电话",hi:"ईमेल या फ़ोन",nl:"E-mail of telefoon",es:"Correo o teléfono",ar:"البريد أو الهاتف",fr:"E-mail ou téléphone",pt:"E-mail ou telefone",id:"Email atau telepon",bn:"ইমেল বা ফোন"},
  "Delete forever": {de:"Endgültig löschen",ru:"Удалить навсегда",zh:"永久删除",hi:"हमेशा के लिए हटाएं",nl:"Definitief verwijderen",es:"Eliminar permanentemente",ar:"حذف نهائيًا",fr:"Supprimer définitivement",pt:"Excluir permanentemente",id:"Hapus permanen",bn:"চিরতরে মুছুন"},
  "How to measure": {de:"So wird gemessen",ru:"Как измерить",zh:"如何测量",hi:"कैसे मापें",nl:"Hoe te meten",es:"Cómo medir",ar:"كيفية القياس",fr:"Comment mesurer",pt:"Como medir",id:"Cara mengukur",bn:"কীভাবে মাপবেন"},
  "Stop listening": {de:"Zuhören beenden",ru:"Остановить прослушивание",zh:"停止聆听",hi:"सुनना बंद करें",nl:"Stop met luisteren",es:"Dejar de escuchar",ar:"إيقاف الاستماع",fr:"Arrêter l'écoute",pt:"Parar de ouvir",id:"Berhenti mendengar",bn:"শোনা বন্ধ করুন"},
  "Use biometrics": {de:"Biometrie verwenden",ru:"Использовать биометрию",zh:"使用生物识别",hi:"बायोमेट्रिक्स उपयोग करें",nl:"Biometrie gebruiken",es:"Usar biometría",ar:"استخدام القياسات الحيوية",fr:"Utiliser la biométrie",pt:"Usar biometria",id:"Gunakan biometrik",bn:"বায়োমেট্রিক্স ব্যবহার করুন"},
  "Enable Location": {de:"Standort aktivieren",ru:"Включить геолокацию",zh:"启用位置",hi:"स्थान सक्षम करें",nl:"Locatie inschakelen",es:"Activar ubicación",ar:"تفعيل الموقع",fr:"Activer la localisation",pt:"Ativar localização",id:"Aktifkan lokasi",bn:"অবস্থান সক্রিয় করুন"},
  "Word of the Day": {de:"Wort des Tages",ru:"Слово дня",zh:"每日一词",hi:"आज का शब्द",nl:"Woord van de dag",es:"Palabra del día",ar:"كلمة اليوم",fr:"Mot du jour",pt:"Palavra do dia",id:"Kata hari ini",bn:"আজকের শব্দ"},
  "Add / Edit Meds": {de:"Medikamente hinzufügen/bearbeiten",ru:"Добавить/изменить лекарства",zh:"添加/编辑药物",hi:"दवाएं जोड़ें/संपादित करें",nl:"Medicijnen toevoegen/bewerken",es:"Añadir/editar medicamentos",ar:"إضافة/تعديل الأدوية",fr:"Ajouter/modifier les médicaments",pt:"Adicionar/editar medicamentos",id:"Tambah/ubah obat",bn:"ওষুধ যোগ/সম্পাদনা"},
  "Auto-lock delay": {de:"Verzögerung der Auto-Sperre",ru:"Задержка автоблокировки",zh:"自动锁定延迟",hi:"ऑटो-लॉक विलंब",nl:"Vertraging automatisch vergrendelen",es:"Retraso de bloqueo automático",ar:"مهلة القفل التلقائي",fr:"Délai de verrouillage auto",pt:"Atraso do bloqueio automático",id:"Jeda kunci otomatis",bn:"অটো-লক বিলম্ব"},
  "Redeem PRO Code": {de:"PRO-Code einlösen",ru:"Активировать PRO-код",zh:"兑换 PRO 代码",hi:"PRO कोड रिडीम करें",nl:"PRO-code inwisselen",es:"Canjear código PRO",ar:"استخدام رمز PRO",fr:"Utiliser un code PRO",pt:"Resgatar código PRO",id:"Tukar kode PRO",bn:"PRO কোড রিডিম করুন"},
  "Connect account": {de:"Konto verbinden",ru:"Подключить аккаунт",zh:"连接账户",hi:"खाता कनेक्ट करें",nl:"Account koppelen",es:"Conectar cuenta",ar:"ربط الحساب",fr:"Connecter le compte",pt:"Conectar conta",id:"Hubungkan akun",bn:"অ্যাকাউন্ট সংযুক্ত করুন"},
  "Select lab test": {de:"Laborwert wählen",ru:"Выбрать анализ",zh:"选择化验项目",hi:"लैब टेस्ट चुनें",nl:"Labtest kiezen",es:"Seleccionar análisis",ar:"اختر التحليل",fr:"Choisir l'analyse",pt:"Selecionar exame",id:"Pilih tes lab",bn:"ল্যাব টেস্ট নির্বাচন করুন"},
  "Conference call": {de:"Konferenzgespräch",ru:"Конференц-звонок",zh:"电话会议",hi:"कॉन्फ्रेंस कॉल",nl:"Groepsgesprek",es:"Llamada en conferencia",ar:"مكالمة جماعية",fr:"Appel en conférence",pt:"Chamada em conferência",id:"Panggilan konferensi",bn:"কনফারেন্স কল"},
  "No messages yet": {de:"Noch keine Nachrichten",ru:"Пока нет сообщений",zh:"暂无消息",hi:"अभी कोई संदेश नहीं",nl:"Nog geen berichten",es:"Aún no hay mensajes",ar:"لا رسائل بعد",fr:"Pas encore de messages",pt:"Ainda sem mensagens",id:"Belum ada pesan",bn:"এখনও কোনো বার্তা নেই"},
  "Private Channel": {de:"Privater Kanal",ru:"Приватный канал",zh:"私人频道",hi:"निजी चैनल",nl:"Privékanaal",es:"Canal privado",ar:"قناة خاصة",fr:"Canal privé",pt:"Canal privado",id:"Saluran pribadi",bn:"ব্যক্তিগত চ্যানেল"},
  "Help & feedback": {de:"Hilfe & Feedback",ru:"Помощь и отзывы",zh:"帮助与反馈",hi:"सहायता और प्रतिक्रिया",nl:"Help & feedback",es:"Ayuda y comentarios",ar:"المساعدة والملاحظات",fr:"Aide et commentaires",pt:"Ajuda e feedback",id:"Bantuan & masukan",bn:"সহায়তা ও মতামত"},
  "Opening camera…": {de:"Kamera wird geöffnet…",ru:"Открытие камеры…",zh:"正在打开相机…",hi:"कैमरा खुल रहा है…",nl:"Camera openen…",es:"Abriendo cámara…",ar:"جارٍ فتح الكاميرا…",fr:"Ouverture de la caméra…",pt:"Abrindo câmera…",id:"Membuka kamera…",bn:"ক্যামেরা খুলছে…"},
  "Main navigation": {de:"Hauptnavigation",ru:"Главная навигация",zh:"主导航",hi:"मुख्य नेविगेशन",nl:"Hoofdnavigatie",es:"Navegación principal",ar:"التنقل الرئيسي",fr:"Navigation principale",pt:"Navegação principal",id:"Navigasi utama",bn:"প্রধান নেভিগেশন"},
  "Voice-first mode": {de:"Sprachmodus",ru:"Голосовой режим",zh:"语音优先模式",hi:"वॉइस-फर्स्ट मोड",nl:"Spraakmodus",es:"Modo de voz",ar:"وضع الصوت أولاً",fr:"Mode voix d'abord",pt:"Modo por voz",id:"Mode suara",bn:"ভয়েস-ফার্স্ট মোড"},
  "Disable & delete": {de:"Deaktivieren & löschen",ru:"Отключить и удалить",zh:"停用并删除",hi:"अक्षम करें और हटाएं",nl:"Uitschakelen & verwijderen",es:"Desactivar y eliminar",ar:"تعطيل وحذف",fr:"Désactiver et supprimer",pt:"Desativar e excluir",id:"Nonaktifkan & hapus",bn:"নিষ্ক্রিয় ও মুছুন"},
  "No readings yet.": {de:"Noch keine Messwerte.",ru:"Пока нет измерений.",zh:"暂无读数。",hi:"अभी कोई रीडिंग नहीं।",nl:"Nog geen metingen.",es:"Aún no hay mediciones.",ar:"لا قراءات بعد.",fr:"Pas encore de mesures.",pt:"Ainda sem leituras.",id:"Belum ada pengukuran.",bn:"এখনও কোনো রিডিং নেই।"},
  "Include this row": {de:"Diese Zeile einschließen",ru:"Включить эту строку",zh:"包含此行",hi:"यह पंक्ति शामिल करें",nl:"Deze rij opnemen",es:"Incluir esta fila",ar:"تضمين هذا الصف",fr:"Inclure cette ligne",pt:"Incluir esta linha",id:"Sertakan baris ini",bn:"এই সারি অন্তর্ভুক্ত করুন"},
  "Content / Result": {de:"Inhalt / Ergebnis",ru:"Содержание / Результат",zh:"内容 / 结果",hi:"सामग्री / परिणाम",nl:"Inhoud / Resultaat",es:"Contenido / Resultado",ar:"المحتوى / النتيجة",fr:"Contenu / Résultat",pt:"Conteúdo / Resultado",id:"Konten / Hasil",bn:"বিষয়বস্তু / ফলাফল"},
  "Take a note...": {de:"Notiz machen…",ru:"Сделать заметку…",zh:"记笔记…",hi:"नोट लें…",nl:"Notitie maken…",es:"Tomar una nota…",ar:"دوّن ملاحظة…",fr:"Prendre une note…",pt:"Fazer uma nota…",id:"Buat catatan…",bn:"একটি নোট নিন…"},

  // ---- Batch 8: medical detail, settings, empty states ----
  "Active ingredient": {de:"Wirkstoff",ru:"Действующее вещество",zh:"活性成分",hi:"सक्रिय घटक",nl:"Werkzame stof",es:"Principio activo",ar:"المادة الفعالة",fr:"Principe actif",pt:"Princípio ativo",id:"Bahan aktif",bn:"সক্রিয় উপাদান"},
  "Chronic Condition": {de:"Chronische Erkrankung",ru:"Хроническое заболевание",zh:"慢性病",hi:"पुरानी बीमारी",nl:"Chronische aandoening",es:"Enfermedad crónica",ar:"حالة مزمنة",fr:"Maladie chronique",pt:"Doença crônica",id:"Kondisi kronis",bn:"দীর্ঘস্থায়ী রোগ"},
  "Health Conditions": {de:"Gesundheitszustände",ru:"Состояния здоровья",zh:"健康状况",hi:"स्वास्थ्य स्थितियां",nl:"Gezondheidsaandoeningen",es:"Condiciones de salud",ar:"الحالات الصحية",fr:"Problèmes de santé",pt:"Condições de saúde",id:"Kondisi kesehatan",bn:"স্বাস্থ্য অবস্থা"},
  "Pulse Measurement": {de:"Pulsmessung",ru:"Измерение пульса",zh:"脉搏测量",hi:"नाड़ी मापन",nl:"Hartslagmeting",es:"Medición del pulso",ar:"قياس النبض",fr:"Mesure du pouls",pt:"Medição do pulso",id:"Pengukuran denyut",bn:"পালস পরিমাপ"},
  "Body Measurements": {de:"Körpermaße",ru:"Измерения тела",zh:"身体测量",hi:"शारीरिक माप",nl:"Lichaamsmetingen",es:"Medidas corporales",ar:"قياسات الجسم",fr:"Mensurations",pt:"Medidas corporais",id:"Pengukuran tubuh",bn:"শারীরিক পরিমাপ"},
  "Active Medications": {de:"Aktive Medikamente",ru:"Активные лекарства",zh:"当前用药",hi:"सक्रिय दवाएं",nl:"Actieve medicijnen",es:"Medicamentos activos",ar:"الأدوية النشطة",fr:"Médicaments actifs",pt:"Medicamentos ativos",id:"Obat aktif",bn:"সক্রিয় ওষুধ"},
  "Quick Symptom Log": {de:"Schnelles Symptom-Log",ru:"Быстрая запись симптома",zh:"快速症状记录",hi:"त्वरित लक्षण लॉग",nl:"Snel symptoomlogboek",es:"Registro rápido de síntomas",ar:"سجل الأعراض السريع",fr:"Journal rapide des symptômes",pt:"Registro rápido de sintomas",id:"Catatan gejala cepat",bn:"দ্রুত উপসর্গ লগ"},
  "Respiration (est.)": {de:"Atmung (geschätzt)",ru:"Дыхание (оценка)",zh:"呼吸 (估算)",hi:"श्वसन (अनुमानित)",nl:"Ademhaling (geschat)",es:"Respiración (est.)",ar:"التنفس (تقديري)",fr:"Respiration (est.)",pt:"Respiração (est.)",id:"Pernapasan (perk.)",bn:"শ্বাস-প্রশ্বাস (আনু.)"},
  "Measurement timing": {de:"Messzeitpunkt",ru:"Время измерения",zh:"测量时机",hi:"मापन समय",nl:"Meetmoment",es:"Momento de la medición",ar:"توقيت القياس",fr:"Moment de la mesure",pt:"Momento da medição",id:"Waktu pengukuran",bn:"পরিমাপের সময়"},
  "Measurement Guides": {de:"Messanleitungen",ru:"Руководства по измерению",zh:"测量指南",hi:"मापन गाइड",nl:"Meethandleidingen",es:"Guías de medición",ar:"أدلة القياس",fr:"Guides de mesure",pt:"Guias de medição",id:"Panduan pengukuran",bn:"পরিমাপ নির্দেশিকা"},
  "Start Balance Test": {de:"Gleichgewichtstest starten",ru:"Начать тест равновесия",zh:"开始平衡测试",hi:"संतुलन परीक्षण शुरू करें",nl:"Balanstest starten",es:"Iniciar prueba de equilibrio",ar:"بدء اختبار التوازن",fr:"Démarrer le test d'équilibre",pt:"Iniciar teste de equilíbrio",id:"Mulai tes keseimbangan",bn:"ভারসাম্য পরীক্ষা শুরু"},
  "Live Step Counting": {de:"Live-Schrittzählung",ru:"Подсчёт шагов в реальном времени",zh:"实时计步",hi:"लाइव स्टेप काउंटिंग",nl:"Live stappen tellen",es:"Conteo de pasos en vivo",ar:"عد الخطوات المباشر",fr:"Comptage de pas en direct",pt:"Contagem de passos ao vivo",id:"Hitung langkah langsung",bn:"লাইভ পদক্ষেপ গণনা"},
  "Cross-device Sync": {de:"Geräteübergreifende Sync",ru:"Синхронизация между устройствами",zh:"跨设备同步",hi:"क्रॉस-डिवाइस सिंक",nl:"Sync tussen apparaten",es:"Sincronización entre dispositivos",ar:"المزامنة بين الأجهزة",fr:"Sync multi-appareils",pt:"Sincronização entre dispositivos",id:"Sinkronisasi antar perangkat",bn:"ক্রস-ডিভাইস সিঙ্ক"},
  "Phone verification": {de:"Telefonverifizierung",ru:"Подтверждение телефона",zh:"电话验证",hi:"फ़ोन सत्यापन",nl:"Telefoonverificatie",es:"Verificación telefónica",ar:"التحقق من الهاتف",fr:"Vérification du téléphone",pt:"Verificação de telefone",id:"Verifikasi telepon",bn:"ফোন যাচাই"},
  "Profanity masking": {de:"Schimpfwortfilter",ru:"Маскировка мата",zh:"脏话屏蔽",hi:"अपशब्द छिपाना",nl:"Scheldwoordfilter",es:"Filtro de groserías",ar:"إخفاء الألفاظ النابية",fr:"Masquage des grossièretés",pt:"Máscara de palavrões",id:"Penyamaran kata kasar",bn:"অশ্লীল শব্দ আড়াল"},
  "Enterprise Inquiry": {de:"Unternehmensanfrage",ru:"Корпоративный запрос",zh:"企业咨询",hi:"एंटरप्राइज़ पूछताछ",nl:"Zakelijke aanvraag",es:"Consulta empresarial",ar:"استفسار المؤسسات",fr:"Demande entreprise",pt:"Consulta corporativa",id:"Pertanyaan perusahaan",bn:"এন্টারপ্রাইজ অনুসন্ধান"},
  "Add to Home Screen": {de:"Zum Startbildschirm hinzufügen",ru:"Добавить на главный экран",zh:"添加到主屏幕",hi:"होम स्क्रीन पर जोड़ें",nl:"Toevoegen aan startscherm",es:"Añadir a pantalla de inicio",ar:"إضافة إلى الشاشة الرئيسية",fr:"Ajouter à l'écran d'accueil",pt:"Adicionar à tela inicial",id:"Tambah ke layar utama",bn:"হোম স্ক্রিনে যোগ করুন"},
  "Install on iPhone": {de:"Auf dem iPhone installieren",ru:"Установить на iPhone",zh:"在 iPhone 上安装",hi:"iPhone पर इंस्टॉल करें",nl:"Installeren op iPhone",es:"Instalar en iPhone",ar:"التثبيت على iPhone",fr:"Installer sur iPhone",pt:"Instalar no iPhone",id:"Pasang di iPhone",bn:"আইফোনে ইনস্টল করুন"},
  "New drawing note": {de:"Neue Zeichennotiz",ru:"Новая заметка-рисунок",zh:"新绘图笔记",hi:"नया ड्रॉइंग नोट",nl:"Nieuwe tekennotitie",es:"Nueva nota de dibujo",ar:"ملاحظة رسم جديدة",fr:"Nouvelle note dessinée",pt:"Nova nota de desenho",id:"Catatan gambar baru",bn:"নতুন অঙ্কন নোট"},
  "Close voice chat": {de:"Sprachchat schließen",ru:"Закрыть голосовой чат",zh:"关闭语音聊天",hi:"वॉइस चैट बंद करें",nl:"Spraakchat sluiten",es:"Cerrar chat de voz",ar:"إغلاق المحادثة الصوتية",fr:"Fermer le chat vocal",pt:"Fechar chat de voz",id:"Tutup obrolan suara",bn:"ভয়েস চ্যাট বন্ধ"},
  "Show my location": {de:"Meinen Standort anzeigen",ru:"Показать моё местоположение",zh:"显示我的位置",hi:"मेरा स्थान दिखाएं",nl:"Mijn locatie tonen",es:"Mostrar mi ubicación",ar:"إظهار موقعي",fr:"Afficher ma position",pt:"Mostrar minha localização",id:"Tampilkan lokasi saya",bn:"আমার অবস্থান দেখান"},
  "Save and go back": {de:"Speichern und zurück",ru:"Сохранить и вернуться",zh:"保存并返回",hi:"सहेजें और वापस जाएं",nl:"Opslaan en terug",es:"Guardar y volver",ar:"حفظ والعودة",fr:"Enregistrer et revenir",pt:"Salvar e voltar",id:"Simpan dan kembali",bn:"সংরক্ষণ করে ফিরুন"},
  "No active alerts": {de:"Keine aktiven Warnungen",ru:"Нет активных оповещений",zh:"无活动提醒",hi:"कोई सक्रिय अलर्ट नहीं",nl:"Geen actieve waarschuwingen",es:"Sin alertas activas",ar:"لا تنبيهات نشطة",fr:"Aucune alerte active",pt:"Sem alertas ativos",id:"Tidak ada peringatan aktif",bn:"কোনো সক্রিয় সতর্কতা নেই"},
  "No matching notes": {de:"Keine passenden Notizen",ru:"Нет подходящих заметок",zh:"没有匹配的笔记",hi:"कोई मेल खाता नोट नहीं",nl:"Geen overeenkomende notities",es:"No hay notas coincidentes",ar:"لا ملاحظات مطابقة",fr:"Aucune note correspondante",pt:"Nenhuma nota correspondente",id:"Tidak ada catatan cocok",bn:"মিলে যাওয়া নোট নেই"},
  "Could not decrypt": {de:"Entschlüsselung fehlgeschlagen",ru:"Не удалось расшифровать",zh:"无法解密",hi:"डिक्रिप्ट नहीं हो सका",nl:"Kon niet ontsleutelen",es:"No se pudo descifrar",ar:"تعذّر فك التشفير",fr:"Impossible de déchiffrer",pt:"Não foi possível descriptografar",id:"Tidak dapat mendekripsi",bn:"ডিক্রিপ্ট করা যায়নি"},
  "Code already used": {de:"Code bereits verwendet",ru:"Код уже использован",zh:"代码已使用",hi:"कोड पहले ही उपयोग हो चुका",nl:"Code al gebruikt",es:"Código ya utilizado",ar:"الرمز مستخدم بالفعل",fr:"Code déjà utilisé",pt:"Código já usado",id:"Kode sudah dipakai",bn:"কোড ইতিমধ্যে ব্যবহৃত"},
  "Enter a group name": {de:"Gruppennamen eingeben",ru:"Введите название группы",zh:"输入群组名称",hi:"समूह का नाम दर्ज करें",nl:"Voer een groepsnaam in",es:"Ingresa un nombre de grupo",ar:"أدخل اسم المجموعة",fr:"Saisir un nom de groupe",pt:"Insira um nome de grupo",id:"Masukkan nama grup",bn:"গ্রুপের নাম দিন"},
  "Search language...": {de:"Sprache suchen…",ru:"Поиск языка…",zh:"搜索语言…",hi:"भाषा खोजें…",nl:"Taal zoeken…",es:"Buscar idioma…",ar:"البحث عن لغة…",fr:"Rechercher une langue…",pt:"Buscar idioma…",id:"Cari bahasa…",bn:"ভাষা খুঁজুন…"},
  "Color & background": {de:"Farbe & Hintergrund",ru:"Цвет и фон",zh:"颜色和背景",hi:"रंग और पृष्ठभूमि",nl:"Kleur & achtergrond",es:"Color y fondo",ar:"اللون والخلفية",fr:"Couleur et arrière-plan",pt:"Cor e fundo",id:"Warna & latar",bn:"রঙ ও পটভূমি"},
  "Guidance complete.": {de:"Anleitung abgeschlossen.",ru:"Инструктаж завершён.",zh:"引导完成。",hi:"मार्गदर्शन पूर्ण।",nl:"Begeleiding voltooid.",es:"Guía completada.",ar:"اكتمل الإرشاد.",fr:"Guidage terminé.",pt:"Orientação concluída.",id:"Panduan selesai.",bn:"নির্দেশনা সম্পূর্ণ।"},
  "Report lower bound": {de:"Untergrenze des Berichts",ru:"Нижняя граница отчёта",zh:"报告下限",hi:"रिपोर्ट निचली सीमा",nl:"Ondergrens rapport",es:"Límite inferior del informe",ar:"الحد الأدنى للتقرير",fr:"Limite inférieure du rapport",pt:"Limite inferior do relatório",id:"Batas bawah laporan",bn:"রিপোর্টের নিম্নসীমা"},
  "Report upper bound": {de:"Obergrenze des Berichts",ru:"Верхняя граница отчёта",zh:"报告上限",hi:"रिपोर्ट ऊपरी सीमा",nl:"Bovengrens rapport",es:"Límite superior del informe",ar:"الحد الأقصى للتقرير",fr:"Limite supérieure du rapport",pt:"Limite superior do relatório",id:"Batas atas laporan",bn:"রিপোর্টের ঊর্ধ্বসীমা"},
  "Weather · details": {de:"Wetter · Details",ru:"Погода · подробнее",zh:"天气 · 详情",hi:"मौसम · विवरण",nl:"Weer · details",es:"Clima · detalles",ar:"الطقس · التفاصيل",fr:"Météo · détails",pt:"Clima · detalhes",id:"Cuaca · detail",bn:"আবহাওয়া · বিস্তারিত"},
  "How to import now?": {de:"Wie jetzt importieren?",ru:"Как импортировать сейчас?",zh:"现在如何导入？",hi:"अभी कैसे आयात करें?",nl:"Hoe nu importeren?",es:"¿Cómo importar ahora?",ar:"كيف أستورد الآن؟",fr:"Comment importer maintenant ?",pt:"Como importar agora?",id:"Bagaimana cara impor sekarang?",bn:"এখন কীভাবে ইমপোর্ট করবেন?"},
};

export const TL = (en, lang) => {
  if (!lang || lang === "tr" || lang === "en") return en;
  const e = TLD[en];
  return (e && e[lang]) || en;
};
