// AILVIE 13-language string layer.
// Core UI is already fully localized via the T dictionary. This layer localizes the many
// inline `lang==="tr"?TR:EN` strings for the other 11 languages. TL(en, lang) returns the
// translation for the current language, or the English source as a safe fallback.
// The dictionary grows in batches; medical/safety-critical strings are reviewed with extra care.
// Languages: de ru zh hi nl es ar fr pt id bn  (tr comes from the ternary; en is the source/fallback)

export const TLD = {
  // ---- Batch 1: high-frequency, context-safe UI words ----
  "Add": {de:"Hinzufügen",ru:"Добавить",zh:"添加",hi:"जोड़ें",nl:"Toevoegen",es:"Añadir",ar:"إضافة",fr:"Ajouter",pt:"Adicionar",id:"Tambah",bn:"যোগ করুন"},
  "Edit": {de:"Bearbeiten",ru:"Изменить",zh:"编辑",hi:"संपादित करें",nl:"Bewerken",es:"Editar",ar:"تعديل",fr:"Modifier",pt:"Editar",id:"Ubah",bn:"সম্পাদনা"},
  "Done": {de:"Fertig",ru:"Готово",zh:"完成",hi:"हो गया",nl:"Klaar",es:"Hecho",ar:"تم",fr:"Terminé",pt:"Concluído",id:"Selesai",bn:"সম্পন্ন"},
  "Copy": {de:"Kopieren",ru:"Копировать",zh:"复制",hi:"कॉपी",nl:"Kopiëren",es:"Copiar",ar:"نسخ",fr:"Copier",pt:"Copiar",id:"Salin",bn:"কপি"},
  "Name": {de:"Name",ru:"Имя",zh:"名称",hi:"नाम",nl:"Naam",es:"Nombre",ar:"الاسم",fr:"Nom",pt:"Nome",id:"Nama",bn:"নাম"},
  "Date": {de:"Datum",ru:"Дата",zh:"日期",hi:"तारीख",nl:"Datum",es:"Fecha",ar:"التاريخ",fr:"Date",pt:"Data",id:"Tanggal",bn:"তারিখ"},
  "Time": {de:"Zeit",ru:"Время",zh:"时间",hi:"समय",nl:"Tijd",es:"Hora",ar:"الوقت",fr:"Heure",pt:"Hora",id:"Waktu",bn:"সময়"},
  "Now": {de:"Jetzt",ru:"Сейчас",zh:"现在",hi:"अभी",nl:"Nu",es:"Ahora",ar:"الآن",fr:"Maintenant",pt:"Agora",id:"Sekarang",bn:"এখন"},
  "On": {de:"An",ru:"Вкл",zh:"开",hi:"चालू",nl:"Aan",es:"Activado",ar:"تشغيل",fr:"Activé",pt:"Ligado",id:"Aktif",bn:"চালু"},
  "Off": {de:"Aus",ru:"Выкл",zh:"关",hi:"बंद",nl:"Uit",es:"Desactivado",ar:"إيقاف",fr:"Désactivé",pt:"Desligado",id:"Nonaktif",bn:"বন্ধ"},
  "All": {de:"Alle",ru:"Все",zh:"全部",hi:"सभी",nl:"Alle",es:"Todos",ar:"الكل",fr:"Tout",pt:"Todos",id:"Semua",bn:"সব"},
  "Soon": {de:"Bald",ru:"Скоро",zh:"即将",hi:"जल्द",nl:"Binnenkort",es:"Pronto",ar:"قريبًا",fr:"Bientôt",pt:"Em breve",id:"Segera",bn:"শীঘ্রই"},
  "Good": {de:"Gut",ru:"Хорошо",zh:"良好",hi:"अच्छा",nl:"Goed",es:"Bien",ar:"جيد",fr:"Bon",pt:"Bom",id:"Baik",bn:"ভালো"},
  "Male": {de:"Männlich",ru:"Мужской",zh:"男",hi:"पुरुष",nl:"Man",es:"Hombre",ar:"ذكر",fr:"Homme",pt:"Masculino",id:"Pria",bn:"পুরুষ"},
  "Call": {de:"Anrufen",ru:"Позвонить",zh:"呼叫",hi:"कॉल",nl:"Bellen",es:"Llamar",ar:"اتصال",fr:"Appeler",pt:"Ligar",id:"Panggil",bn:"কল"},
  "Left": {de:"Übrig",ru:"Осталось",zh:"剩余",hi:"बाकी",nl:"Over",es:"Restante",ar:"متبقٍ",fr:"Restant",pt:"Restante",id:"Sisa",bn:"বাকি"},
  "Mood": {de:"Stimmung",ru:"Настроение",zh:"心情",hi:"मूड",nl:"Stemming",es:"Ánimo",ar:"المزاج",fr:"Humeur",pt:"Humor",id:"Suasana hati",bn:"মেজাজ"},
  "Live": {de:"Live",ru:"Онлайн",zh:"实时",hi:"लाइव",nl:"Live",es:"En vivo",ar:"مباشر",fr:"En direct",pt:"Ao vivo",id:"Langsung",bn:"লাইভ"},
  "Fast": {de:"Schnell",ru:"Быстро",zh:"快",hi:"तेज़",nl:"Snel",es:"Rápido",ar:"سريع",fr:"Rapide",pt:"Rápido",id:"Cepat",bn:"দ্রুত"},
  "Slow": {de:"Langsam",ru:"Медленно",zh:"慢",hi:"धीमा",nl:"Langzaam",es:"Lento",ar:"بطيء",fr:"Lent",pt:"Lento",id:"Lambat",bn:"ধীর"},
  "Wake": {de:"Aufwachen",ru:"Подъём",zh:"起床",hi:"जागना",nl:"Wakker",es:"Despertar",ar:"الاستيقاظ",fr:"Réveil",pt:"Acordar",id:"Bangun",bn:"জাগরণ"},
  "Taxi": {de:"Taxi",ru:"Такси",zh:"出租车",hi:"टैक्सी",nl:"Taxi",es:"Taxi",ar:"سيارة أجرة",fr:"Taxi",pt:"Táxi",id:"Taksi",bn:"ট্যাক্সি"},

  // ---- Batch 2: common readable UI phrases ----
  "Signed out": {de:"Abgemeldet",ru:"Выход выполнен",zh:"已退出",hi:"साइन आउट",nl:"Afgemeld",es:"Sesión cerrada",ar:"تم تسجيل الخروج",fr:"Déconnecté",pt:"Sessão encerrada",id:"Keluar",bn:"সাইন আউট"},
  "Signed in": {de:"Angemeldet",ru:"Вход выполнен",zh:"已登录",hi:"साइन इन",nl:"Aangemeld",es:"Sesión iniciada",ar:"تم تسجيل الدخول",fr:"Connecté",pt:"Sessão iniciada",id:"Masuk",bn:"সাইন ইন"},
  "Enter data": {de:"Daten eingeben",ru:"Ввести данные",zh:"输入数据",hi:"डेटा दर्ज करें",nl:"Gegevens invoeren",es:"Ingresar datos",ar:"إدخال البيانات",fr:"Saisir des données",pt:"Inserir dados",id:"Masukkan data",bn:"তথ্য দিন"},
  "Taken Meds": {de:"Eingenommene Medikamente",ru:"Принятые лекарства",zh:"已服药物",hi:"ली गई दवाएं",nl:"Ingenomen medicijnen",es:"Medicamentos tomados",ar:"الأدوية المتناولة",fr:"Médicaments pris",pt:"Medicamentos tomados",id:"Obat yang diminum",bn:"নেওয়া ওষুধ"},
  "How to use": {de:"Anleitung",ru:"Как пользоваться",zh:"使用方法",hi:"उपयोग कैसे करें",nl:"Hoe te gebruiken",es:"Cómo usar",ar:"كيفية الاستخدام",fr:"Comment utiliser",pt:"Como usar",id:"Cara pakai",bn:"যেভাবে ব্যবহার করবেন"},
  "Identifier": {de:"Kennung",ru:"Идентификатор",zh:"标识符",hi:"पहचानकर्ता",nl:"Identificatie",es:"Identificador",ar:"المعرّف",fr:"Identifiant",pt:"Identificador",id:"Pengenal",bn:"শনাক্তকারী"},
  "Biometrics": {de:"Biometrie",ru:"Биометрия",zh:"生物识别",hi:"बायोमेट्रिक्स",nl:"Biometrie",es:"Biometría",ar:"القياسات الحيوية",fr:"Biométrie",pt:"Biometria",id:"Biometrik",bn:"বায়োমেট্রিক্স"},
  "Contact Us": {de:"Kontakt",ru:"Связаться с нами",zh:"联系我们",hi:"संपर्क करें",nl:"Contact",es:"Contáctanos",ar:"اتصل بنا",fr:"Nous contacter",pt:"Fale conosco",id:"Hubungi kami",bn:"যোগাযোগ করুন"},
  "Empty note": {de:"Leere Notiz",ru:"Пустая заметка",zh:"空笔记",hi:"खाली नोट",nl:"Lege notitie",es:"Nota vacía",ar:"ملاحظة فارغة",fr:"Note vide",pt:"Nota vazia",id:"Catatan kosong",bn:"খালি নোট"},
  "Overweight": {de:"Übergewicht",ru:"Избыточный вес",zh:"超重",hi:"अधिक वजन",nl:"Overgewicht",es:"Sobrepeso",ar:"زيادة الوزن",fr:"Surpoids",pt:"Sobrepeso",id:"Kelebihan berat badan",bn:"অতিরিক্ত ওজন"},
  "Connection": {de:"Verbindung",ru:"Подключение",zh:"连接",hi:"कनेक्शन",nl:"Verbinding",es:"Conexión",ar:"الاتصال",fr:"Connexion",pt:"Conexão",id:"Koneksi",bn:"সংযোগ"},
  "Take photo": {de:"Foto aufnehmen",ru:"Сделать фото",zh:"拍照",hi:"फोटो लें",nl:"Foto maken",es:"Tomar foto",ar:"التقاط صورة",fr:"Prendre une photo",pt:"Tirar foto",id:"Ambil foto",bn:"ছবি তুলুন"},
  "Disconnect": {de:"Trennen",ru:"Отключить",zh:"断开",hi:"डिस्कनेक्ट",nl:"Verbreken",es:"Desconectar",ar:"قطع الاتصال",fr:"Déconnecter",pt:"Desconectar",id:"Putuskan",bn:"বিচ্ছিন্ন করুন"},
  "Test again": {de:"Erneut testen",ru:"Повторить тест",zh:"重新测试",hi:"फिर से जांचें",nl:"Opnieuw testen",es:"Probar de nuevo",ar:"إعادة الاختبار",fr:"Retester",pt:"Testar novamente",id:"Uji lagi",bn:"আবার পরীক্ষা করুন"},
  "New Record": {de:"Neuer Eintrag",ru:"Новая запись",zh:"新记录",hi:"नया रिकॉर्ड",nl:"Nieuw record",es:"Nuevo registro",ar:"سجل جديد",fr:"Nouvel enregistrement",pt:"Novo registro",id:"Catatan baru",bn:"নতুন রেকর্ড"},
  "Voice call": {de:"Sprachanruf",ru:"Голосовой вызов",zh:"语音通话",hi:"वॉइस कॉल",nl:"Spraakoproep",es:"Llamada de voz",ar:"مكالمة صوتية",fr:"Appel vocal",pt:"Chamada de voz",id:"Panggilan suara",bn:"ভয়েস কল"},
  "Video call": {de:"Videoanruf",ru:"Видеозвонок",zh:"视频通话",hi:"वीडियो कॉल",nl:"Videogesprek",es:"Videollamada",ar:"مكالمة فيديو",fr:"Appel vidéo",pt:"Videochamada",id:"Panggilan video",bn:"ভিডিও কল"},
  "Conference": {de:"Konferenz",ru:"Конференция",zh:"会议",hi:"कॉन्फ्रेंस",nl:"Vergadering",es:"Conferencia",ar:"مؤتمر",fr:"Conférence",pt:"Conferência",id:"Konferensi",bn:"কনফারেন্স"},
  "Group name": {de:"Gruppenname",ru:"Название группы",zh:"群组名称",hi:"समूह का नाम",nl:"Groepsnaam",es:"Nombre del grupo",ar:"اسم المجموعة",fr:"Nom du groupe",pt:"Nome do grupo",id:"Nama grup",bn:"গ্রুপের নাম"},
  "Navigation": {de:"Navigation",ru:"Навигация",zh:"导航",hi:"नेविगेशन",nl:"Navigatie",es:"Navegación",ar:"الملاحة",fr:"Navigation",pt:"Navegação",id:"Navigasi",bn:"নেভিগেশন"},
  "Background": {de:"Hintergrund",ru:"Фон",zh:"背景",hi:"पृष्ठभूमि",nl:"Achtergrond",es:"Fondo",ar:"الخلفية",fr:"Arrière-plan",pt:"Fundo",id:"Latar belakang",bn:"পটভূমি"},
  "Formatting": {de:"Formatierung",ru:"Форматирование",zh:"格式",hi:"फ़ॉर्मेटिंग",nl:"Opmaak",es:"Formato",ar:"التنسيق",fr:"Mise en forme",pt:"Formatação",id:"Pemformatan",bn:"ফরম্যাটিং"},
  "Reset zoom": {de:"Zoom zurücksetzen",ru:"Сбросить масштаб",zh:"重置缩放",hi:"ज़ूम रीसेट करें",nl:"Zoom resetten",es:"Restablecer zoom",ar:"إعادة ضبط التكبير",fr:"Réinitialiser le zoom",pt:"Redefinir zoom",id:"Atur ulang zoom",bn:"জুম রিসেট"},
  "My account": {de:"Mein Konto",ru:"Мой аккаунт",zh:"我的账户",hi:"मेरा खाता",nl:"Mijn account",es:"Mi cuenta",ar:"حسابي",fr:"Mon compte",pt:"Minha conta",id:"Akun saya",bn:"আমার অ্যাকাউন্ট"},
  "Live Health": {de:"Live-Gesundheit",ru:"Здоровье в реальном времени",zh:"实时健康",hi:"लाइव हेल्थ",nl:"Live gezondheid",es:"Salud en vivo",ar:"الصحة المباشرة",fr:"Santé en direct",pt:"Saúde ao vivo",id:"Kesehatan langsung",bn:"লাইভ স্বাস্থ্য"},
  "Unlock sync": {de:"Sync entsperren",ru:"Разблокировать синхронизацию",zh:"解锁同步",hi:"सिंक अनलॉक करें",nl:"Sync ontgrendelen",es:"Desbloquear sincronización",ar:"فتح المزامنة",fr:"Déverrouiller la sync",pt:"Desbloquear sincronização",id:"Buka kunci sinkronisasi",bn:"সিঙ্ক আনলক"},
  "Remove lock": {de:"Sperre entfernen",ru:"Убрать блокировку",zh:"移除锁定",hi:"लॉक हटाएं",nl:"Vergrendeling verwijderen",es:"Quitar bloqueo",ar:"إزالة القفل",fr:"Supprimer le verrou",pt:"Remover bloqueio",id:"Hapus kunci",bn:"লক সরান"},
  "Active Plan": {de:"Aktiver Plan",ru:"Активный план",zh:"当前套餐",hi:"सक्रिय योजना",nl:"Actief abonnement",es:"Plan activo",ar:"الخطة النشطة",fr:"Forfait actif",pt:"Plano ativo",id:"Paket aktif",bn:"সক্রিয় প্ল্যান"},
  "Data Backup": {de:"Datensicherung",ru:"Резервная копия",zh:"数据备份",hi:"डेटा बैकअप",nl:"Gegevensback-up",es:"Copia de seguridad",ar:"نسخ البيانات احتياطيًا",fr:"Sauvegarde des données",pt:"Backup de dados",id:"Cadangan data",bn:"ডেটা ব্যাকআপ"},
  "Select meal": {de:"Mahlzeit wählen",ru:"Выбрать приём пищи",zh:"选择餐次",hi:"भोजन चुनें",nl:"Maaltijd kiezen",es:"Seleccionar comida",ar:"اختر الوجبة",fr:"Choisir un repas",pt:"Selecionar refeição",id:"Pilih makanan",bn:"খাবার নির্বাচন করুন"},
  "Add Reading": {de:"Messwert hinzufügen",ru:"Добавить измерение",zh:"添加读数",hi:"रीडिंग जोड़ें",nl:"Meting toevoegen",es:"Añadir medición",ar:"إضافة قراءة",fr:"Ajouter une mesure",pt:"Adicionar leitura",id:"Tambah pengukuran",bn:"রিডিং যোগ করুন"},
  "Goal weight": {de:"Zielgewicht",ru:"Целевой вес",zh:"目标体重",hi:"लक्ष्य वजन",nl:"Streefgewicht",es:"Peso objetivo",ar:"الوزن المستهدف",fr:"Poids cible",pt:"Peso alvo",id:"Berat target",bn:"লক্ষ্য ওজন"},
  "Vital Signs": {de:"Vitalzeichen",ru:"Показатели жизнедеятельности",zh:"生命体征",hi:"महत्वपूर्ण संकेत",nl:"Vitale functies",es:"Signos vitales",ar:"العلامات الحيوية",fr:"Signes vitaux",pt:"Sinais vitais",id:"Tanda vital",bn:"শারীরিক লক্ষণ"},
  "Vital signs": {de:"Vitalzeichen",ru:"Показатели жизнедеятельности",zh:"生命体征",hi:"महत्वपूर्ण संकेत",nl:"Vitale functies",es:"Signos vitales",ar:"العلامات الحيوية",fr:"Signes vitaux",pt:"Sinais vitais",id:"Tanda vital",bn:"শারীরিক লক্ষণ"},
  "Last 7 days": {de:"Letzte 7 Tage",ru:"Последние 7 дней",zh:"最近7天",hi:"पिछले 7 दिन",nl:"Laatste 7 dagen",es:"Últimos 7 días",ar:"آخر 7 أيام",fr:"7 derniers jours",pt:"Últimos 7 dias",id:"7 hari terakhir",bn:"গত ৭ দিন"},
  "New group": {de:"Neue Gruppe",ru:"Новая группа",zh:"新群组",hi:"नया समूह",nl:"Nieuwe groep",es:"Nuevo grupo",ar:"مجموعة جديدة",fr:"Nouveau groupe",pt:"Novo grupo",id:"Grup baru",bn:"নতুন গ্রুপ"},
  "Underweight": {de:"Untergewicht",ru:"Недостаточный вес",zh:"体重过轻",hi:"कम वजन",nl:"Ondergewicht",es:"Bajo peso",ar:"نقص الوزن",fr:"Insuffisance pondérale",pt:"Abaixo do peso",id:"Berat badan kurang",bn:"কম ওজন"},
  "Add photo": {de:"Foto hinzufügen",ru:"Добавить фото",zh:"添加照片",hi:"फोटो जोड़ें",nl:"Foto toevoegen",es:"Añadir foto",ar:"إضافة صورة",fr:"Ajouter une photo",pt:"Adicionar foto",id:"Tambah foto",bn:"ছবি যোগ করুন"},
  "Try again": {de:"Erneut versuchen",ru:"Повторить",zh:"重试",hi:"पुनः प्रयास करें",nl:"Opnieuw proberen",es:"Reintentar",ar:"حاول مرة أخرى",fr:"Réessayer",pt:"Tentar novamente",id:"Coba lagi",bn:"আবার চেষ্টা করুন"},
  "Delete all": {de:"Alle löschen",ru:"Удалить все",zh:"全部删除",hi:"सभी हटाएं",nl:"Alles verwijderen",es:"Eliminar todo",ar:"حذف الكل",fr:"Tout supprimer",pt:"Excluir tudo",id:"Hapus semua",bn:"সব মুছুন"},

  // ---- Batch 3: dialogs, actions, health labels ----
  "Coming soon": {de:"Bald verfügbar",ru:"Скоро",zh:"即将推出",hi:"जल्द आ रहा है",nl:"Binnenkort",es:"Próximamente",ar:"قريبًا",fr:"Bientôt disponible",pt:"Em breve",id:"Segera hadir",bn:"শীঘ্রই আসছে"},
  "No compass": {de:"Kein Kompass",ru:"Нет компаса",zh:"无指南针",hi:"कोई कम्पास नहीं",nl:"Geen kompas",es:"Sin brújula",ar:"لا توجد بوصلة",fr:"Pas de boussole",pt:"Sem bússola",id:"Tidak ada kompas",bn:"কম্পাস নেই"},
  "Enterprise": {de:"Unternehmen",ru:"Корпоративный",zh:"企业版",hi:"एंटरप्राइज़",nl:"Zakelijk",es:"Empresas",ar:"للمؤسسات",fr:"Entreprise",pt:"Corporativo",id:"Perusahaan",bn:"এন্টারপ্রাইজ"},
  "Checkboxes": {de:"Kontrollkästchen",ru:"Флажки",zh:"复选框",hi:"चेकबॉक्स",nl:"Selectievakjes",es:"Casillas",ar:"مربعات الاختيار",fr:"Cases à cocher",pt:"Caixas de seleção",id:"Kotak centang",bn:"চেকবক্স"},
  "Lower bound": {de:"Untergrenze",ru:"Нижняя граница",zh:"下限",hi:"निचली सीमा",nl:"Ondergrens",es:"Límite inferior",ar:"الحد الأدنى",fr:"Limite inférieure",pt:"Limite inferior",id:"Batas bawah",bn:"নিম্নসীমা"},
  "Upper bound": {de:"Obergrenze",ru:"Верхняя граница",zh:"上限",hi:"ऊपरी सीमा",nl:"Bovengrens",es:"Límite superior",ar:"الحد الأقصى",fr:"Limite supérieure",pt:"Limite superior",id:"Batas atas",bn:"ঊর্ধ্বসীমা"},
  "Select unit": {de:"Einheit wählen",ru:"Выбрать единицу",zh:"选择单位",hi:"इकाई चुनें",nl:"Eenheid kiezen",es:"Seleccionar unidad",ar:"اختر الوحدة",fr:"Choisir l'unité",pt:"Selecionar unidade",id:"Pilih satuan",bn:"একক নির্বাচন"},
  "Edit Record": {de:"Eintrag bearbeiten",ru:"Изменить запись",zh:"编辑记录",hi:"रिकॉर्ड संपादित करें",nl:"Record bewerken",es:"Editar registro",ar:"تعديل السجل",fr:"Modifier l'enregistrement",pt:"Editar registro",id:"Ubah catatan",bn:"রেকর্ড সম্পাদনা"},
  "New Contact": {de:"Neuer Kontakt",ru:"Новый контакт",zh:"新联系人",hi:"नया संपर्क",nl:"Nieuw contact",es:"Nuevo contacto",ar:"جهة اتصال جديدة",fr:"Nouveau contact",pt:"Novo contato",id:"Kontak baru",bn:"নতুন পরিচিতি"},
  "Make a copy": {de:"Kopie erstellen",ru:"Создать копию",zh:"创建副本",hi:"प्रतिलिपि बनाएं",nl:"Kopie maken",es:"Hacer una copia",ar:"إنشاء نسخة",fr:"Créer une copie",pt:"Fazer uma cópia",id:"Buat salinan",bn:"অনুলিপি তৈরি করুন"},
  "Pick colour": {de:"Farbe wählen",ru:"Выбрать цвет",zh:"选择颜色",hi:"रंग चुनें",nl:"Kleur kiezen",es:"Elegir color",ar:"اختر اللون",fr:"Choisir la couleur",pt:"Escolher cor",id:"Pilih warna",bn:"রঙ নির্বাচন করুন"},
  "Highlighter": {de:"Textmarker",ru:"Маркер",zh:"荧光笔",hi:"हाइलाइटर",nl:"Markeerstift",es:"Resaltador",ar:"قلم تحديد",fr:"Surligneur",pt:"Marca-texto",id:"Stabilo",bn:"হাইলাইটার"},
  "Pulse + HRV": {de:"Puls + HRV",ru:"Пульс + HRV",zh:"脉搏 + HRV",hi:"नाड़ी + HRV",nl:"Hartslag + HRV",es:"Pulso + HRV",ar:"النبض + HRV",fr:"Pouls + HRV",pt:"Pulso + HRV",id:"Denyut + HRV",bn:"পালস + HRV"},
  "No response.": {de:"Keine Antwort.",ru:"Нет ответа.",zh:"无响应。",hi:"कोई प्रतिक्रिया नहीं।",nl:"Geen reactie.",es:"Sin respuesta.",ar:"لا يوجد رد.",fr:"Aucune réponse.",pt:"Sem resposta.",id:"Tidak ada respons.",bn:"কোনো সাড়া নেই।"},
  "Voice typing": {de:"Spracheingabe",ru:"Голосовой ввод",zh:"语音输入",hi:"वॉइस टाइपिंग",nl:"Spraakinvoer",es:"Dictado por voz",ar:"الكتابة الصوتية",fr:"Saisie vocale",pt:"Digitação por voz",id:"Ketik dengan suara",bn:"ভয়েস টাইপিং"},
  "Pending Meds": {de:"Ausstehende Medikamente",ru:"Ожидающие лекарства",zh:"待服药物",hi:"लंबित दवाएं",nl:"Openstaande medicijnen",es:"Medicamentos pendientes",ar:"أدوية معلّقة",fr:"Médicaments en attente",pt:"Medicamentos pendentes",id:"Obat tertunda",bn:"বাকি ওষুধ"},
  "Add Manually": {de:"Manuell hinzufügen",ru:"Добавить вручную",zh:"手动添加",hi:"मैन्युअल रूप से जोड़ें",nl:"Handmatig toevoegen",es:"Añadir manualmente",ar:"إضافة يدويًا",fr:"Ajouter manuellement",pt:"Adicionar manualmente",id:"Tambah manual",bn:"ম্যানুয়ালি যোগ করুন"},
  "Repeat daily": {de:"Täglich wiederholen",ru:"Повторять ежедневно",zh:"每日重复",hi:"रोज़ दोहराएं",nl:"Dagelijks herhalen",es:"Repetir a diario",ar:"تكرار يوميًا",fr:"Répéter chaque jour",pt:"Repetir diariamente",id:"Ulangi harian",bn:"প্রতিদিন পুনরাবৃত্তি"},
  "Current plan": {de:"Aktueller Plan",ru:"Текущий план",zh:"当前套餐",hi:"वर्तमान योजना",nl:"Huidig abonnement",es:"Plan actual",ar:"الخطة الحالية",fr:"Forfait actuel",pt:"Plano atual",id:"Paket saat ini",bn:"বর্তমান প্ল্যান"},
  "Enter a code": {de:"Code eingeben",ru:"Введите код",zh:"输入代码",hi:"कोड दर्ज करें",nl:"Voer een code in",es:"Ingresa un código",ar:"أدخل رمزًا",fr:"Saisir un code",pt:"Inserir um código",id:"Masukkan kode",bn:"একটি কোড দিন"},
  "Invalid code": {de:"Ungültiger Code",ru:"Неверный код",zh:"无效代码",hi:"अमान्य कोड",nl:"Ongeldige code",es:"Código no válido",ar:"رمز غير صالح",fr:"Code invalide",pt:"Código inválido",id:"Kode tidak valid",bn:"অবৈধ কোড"},
  "Diet Program": {de:"Ernährungsplan",ru:"Программа питания",zh:"饮食计划",hi:"आहार कार्यक्रम",nl:"Dieetprogramma",es:"Programa de dieta",ar:"برنامج غذائي",fr:"Programme diététique",pt:"Programa de dieta",id:"Program diet",bn:"ডায়েট প্রোগ্রাম"},
  "Imaging type": {de:"Bildgebungstyp",ru:"Тип исследования",zh:"影像类型",hi:"इमेजिंग प्रकार",nl:"Type beeldvorming",es:"Tipo de imagen",ar:"نوع التصوير",fr:"Type d'imagerie",pt:"Tipo de imagem",id:"Jenis pencitraan",bn:"ইমেজিং ধরন"},
  "Choose files": {de:"Dateien auswählen",ru:"Выбрать файлы",zh:"选择文件",hi:"फ़ाइलें चुनें",nl:"Bestanden kiezen",es:"Elegir archivos",ar:"اختر الملفات",fr:"Choisir des fichiers",pt:"Escolher arquivos",id:"Pilih file",bn:"ফাইল নির্বাচন করুন"},
  "Water Intake": {de:"Wasseraufnahme",ru:"Потребление воды",zh:"饮水量",hi:"पानी का सेवन",nl:"Waterinname",es:"Consumo de agua",ar:"كمية الماء",fr:"Consommation d'eau",pt:"Consumo de água",id:"Asupan air",bn:"পানি গ্রহণ"},
  "Tap to start": {de:"Zum Starten tippen",ru:"Нажмите, чтобы начать",zh:"点击开始",hi:"शुरू करने के लिए टैप करें",nl:"Tik om te starten",es:"Toca para empezar",ar:"اضغط للبدء",fr:"Appuyez pour démarrer",pt:"Toque para iniciar",id:"Ketuk untuk mulai",bn:"শুরু করতে ট্যাপ করুন"},
  "Value slider": {de:"Wert-Schieberegler",ru:"Ползунок значения",zh:"数值滑块",hi:"मान स्लाइडर",nl:"Waardeschuif",es:"Control deslizante",ar:"شريط تمرير القيمة",fr:"Curseur de valeur",pt:"Controle de valor",id:"Penggeser nilai",bn:"মান স্লাইডার"},
  "Add Record": {de:"Eintrag hinzufügen",ru:"Добавить запись",zh:"添加记录",hi:"रिकॉर्ड जोड़ें",nl:"Record toevoegen",es:"Añadir registro",ar:"إضافة سجل",fr:"Ajouter un enregistrement",pt:"Adicionar registro",id:"Tambah catatan",bn:"রেকর্ড যোগ করুন"},
  "Repeat weekly": {de:"Wöchentlich wiederholen",ru:"Повторять еженедельно",zh:"每周重复",hi:"साप्ताहिक दोहराएं",nl:"Wekelijks herhalen",es:"Repetir semanalmente",ar:"تكرار أسبوعيًا",fr:"Répéter chaque semaine",pt:"Repetir semanalmente",id:"Ulangi mingguan",bn:"সাপ্তাহিক পুনরাবৃত্তি"},
  "Blood sugar": {de:"Blutzucker",ru:"Сахар в крови",zh:"血糖",hi:"रक्त शर्करा",nl:"Bloedsuiker",es:"Azúcar en sangre",ar:"سكر الدم",fr:"Glycémie",pt:"Açúcar no sangue",id:"Gula darah",bn:"রক্তে শর্করা"},
  "Heart rate": {de:"Herzfrequenz",ru:"Частота пульса",zh:"心率",hi:"हृदय गति",nl:"Hartslag",es:"Frecuencia cardíaca",ar:"معدل ضربات القلب",fr:"Fréquence cardiaque",pt:"Frequência cardíaca",id:"Detak jantung",bn:"হৃদস্পন্দন"},
  "Body temp": {de:"Körpertemperatur",ru:"Температура тела",zh:"体温",hi:"शरीर का तापमान",nl:"Lichaamstemp",es:"Temp. corporal",ar:"درجة حرارة الجسم",fr:"Température corporelle",pt:"Temp. corporal",id:"Suhu tubuh",bn:"শরীরের তাপমাত্রা"},
  "Save note": {de:"Notiz speichern",ru:"Сохранить заметку",zh:"保存笔记",hi:"नोट सहेजें",nl:"Notitie opslaan",es:"Guardar nota",ar:"حفظ الملاحظة",fr:"Enregistrer la note",pt:"Salvar nota",id:"Simpan catatan",bn:"নোট সংরক্ষণ"},
  "New note": {de:"Neue Notiz",ru:"Новая заметка",zh:"新笔记",hi:"नया नोट",nl:"Nieuwe notitie",es:"Nueva nota",ar:"ملاحظة جديدة",fr:"Nouvelle note",pt:"Nova nota",id:"Catatan baru",bn:"নতুন নোট"},
  "Reminders": {de:"Erinnerungen",ru:"Напоминания",zh:"提醒",hi:"रिमाइंडर",nl:"Herinneringen",es:"Recordatorios",ar:"التذكيرات",fr:"Rappels",pt:"Lembretes",id:"Pengingat",bn:"রিমাইন্ডার"},
  "Allergies": {de:"Allergien",ru:"Аллергии",zh:"过敏",hi:"एलर्जी",nl:"Allergieën",es:"Alergias",ar:"الحساسية",fr:"Allergies",pt:"Alergias",id:"Alergi",bn:"অ্যালার্জি"},
  "Emergency": {de:"Notfall",ru:"Экстренная помощь",zh:"紧急",hi:"आपातकाल",nl:"Noodgeval",es:"Emergencia",ar:"طوارئ",fr:"Urgence",pt:"Emergência",id:"Darurat",bn:"জরুরি"},
};

export const TL = (en, lang) => {
  if (!lang || lang === "tr" || lang === "en") return en;
  const e = TLD[en];
  return (e && e[lang]) || en;
};
